"""
大规模TikTok URL补充
"""
import sqlite3
import os

DB_PATH = os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))), 'data', 'competitive_research.db')

tiktok_map = {
    # A
    'other-stories-na': 'https://www.tiktok.com/@andotherstories',
    '2xu': 'https://www.tiktok.com/@2xu',
    '7-for-all-mankind-na': 'https://www.tiktok.com/@7forallmankind',
    'apc-na': 'https://www.tiktok.com/@apc_paris',
    'ag-jeans': 'https://www.tiktok.com/@agjeans',
    'ag-jeans-na': 'https://www.tiktok.com/@agjeans',
    'asics-na': 'https://www.tiktok.com/@asics',
    'aybl': 'https://www.tiktok.com/@aybl',
    'abercrombie-fitch': 'https://www.tiktok.com/@abercrombie',
    'acne-studios-na': 'https://www.tiktok.com/@acnestudios',
    'aday': 'https://www.tiktok.com/@aday',
    'adidas-na': 'https://www.tiktok.com/@adidas',
    'aether-apparel': 'https://www.tiktok.com/@aetherapparel',
    'aime-leon-dore': 'https://www.tiktok.com/@aimeleondore',
    'aldo': 'https://www.tiktok.com/@aldo_shoes',
    'aldo-na': 'https://www.tiktok.com/@aldo_shoes',
    'alex-and-ani': 'https://www.tiktok.com/@alexandani',
    'alexander-wang-na': 'https://www.tiktok.com/@alexanderwangny',
    'alice-and-olivia': 'https://www.tiktok.com/@aliceandolivia',
    'allbirds-na': 'https://www.tiktok.com/@allbirds',
    'altra': 'https://www.tiktok.com/@altra',
    'altuzarra-na': 'https://www.tiktok.com/@altuzarra',
    'amour-vert': 'https://www.tiktok.com/@amourvert',
    'ana-luisa': 'https://www.tiktok.com/@analuisanyc',
    'angel-dear': 'https://www.tiktok.com/@angeldear',
    'athleta': 'https://www.tiktok.com/@athleta',
    'away-travel': 'https://www.tiktok.com/@away',
    
    # B
    'babolat': 'https://www.tiktok.com/@babolat',
    'babolat-na': 'https://www.tiktok.com/@babolat',
    'baboon-to-the-moon': 'https://www.tiktok.com/@baboontothemoon',
    'balega': 'https://www.tiktok.com/@balega',
    'balenciaga-na': 'https://www.tiktok.com/@balenciaga',
    'bally-na': 'https://www.tiktok.com/@bally',
    'balmain-na': 'https://www.tiktok.com/@balmain',
    'banana-republic': 'https://www.tiktok.com/@bananarepublic',
    'bandit-running': 'https://www.tiktok.com/@banditrunning',
    'bass-pro-cabelas': 'https://www.tiktok.com/@bassproshops',
    'baublebar': 'https://www.tiktok.com/@baublebar',
    'beckett-simonon': 'https://www.tiktok.com/@beckettsimonon',
    'bellroy': 'https://www.tiktok.com/@bellroy',
    'beyond-yoga': 'https://www.tiktok.com/@beyondyoga',
    'birddogs-na': 'https://www.tiktok.com/@birddogs',
    'birdies': 'https://www.tiktok.com/@birdies',
    'birkenstock-na': 'https://www.tiktok.com/@birkenstock',
    'birkenstock-1774': 'https://www.tiktok.com/@birkenstock',
    'black-diamond': 'https://www.tiktok.com/@blackdiamond',
    'blundstone-na': 'https://www.tiktok.com/@blundstone',
    'bogs': 'https://www.tiktok.com/@bogsfootwear',
    'boll-and-branch': 'https://www.tiktok.com/@bollandbranch',
    'bombshell-sportswear': 'https://www.tiktok.com/@bombshellsport',
    'bonobos': 'https://www.tiktok.com/@bonobos',
    'bonobos-na': 'https://www.tiktok.com/@bonobos',
    'boss-na': 'https://www.tiktok.com/@boss',
    'bottega-veneta-na': 'https://www.tiktok.com/@bottegaveneta',
    'breitling-na': 'https://www.tiktok.com/@breitling',
    'brooks': 'https://www.tiktok.com/@brooksrunning',
    'brooks-running': 'https://www.tiktok.com/@brooksrunning',
    'brooklinen': 'https://www.tiktok.com/@brooklinen',
    'brunello-cucinelli-na': 'https://www.tiktok.com/@brunellocucinelli',
    'brunello-cucinelli': 'https://www.tiktok.com/@brunellocucinelli',
    'burberry-na': 'https://www.tiktok.com/@burberry',
    'burton': 'https://www.tiktok.com/@burton',
    'bylt-basics': 'https://www.tiktok.com/@byltbasics',
    'buck-mason': 'https://www.tiktok.com/@buckmason',
    'burts-bees-baby': 'https://www.tiktok.com/@burtsbeesbaby',
    'beis': 'https://www.tiktok.com/@beis',
    
    # C
    'campsnap': 'https://www.tiktok.com/@campsnapcamera',
    'canada-goose': 'https://www.tiktok.com/@canadagoose',
    'carhartt-na': 'https://www.tiktok.com/@carhartt',
    'cariuma': 'https://www.tiktok.com/@cariuma',
    'cartier-na': 'https://www.tiktok.com/@cartier',
    'casio-na': 'https://www.tiktok.com/@casio',
    'celine-na': 'https://www.tiktok.com/@celine',
    'chaco': 'https://www.tiktok.com/@chacofootwear',
    'chanel-na': 'https://www.tiktok.com/@chanel',
    'chicos': 'https://www.tiktok.com/@chicos',
    'chloe-na': 'https://www.tiktok.com/@chloe',
    'chubbies': 'https://www.tiktok.com/@chubbies',
    'champion': 'https://www.tiktok.com/@champion',
    'champion-na': 'https://www.tiktok.com/@champion',
    'coach-na': 'https://www.tiktok.com/@coach',
    'cole-haan-na': 'https://www.tiktok.com/@colehaan',
    'columbia-sportswear': 'https://www.tiktok.com/@columbia1938',
    'cotopaxi': 'https://www.tiktok.com/@cotopaxi',
    'crap-eyewear-na': 'https://www.tiktok.com/@crapeyewear',
    'crz-yoga': 'https://www.tiktok.com/@crzyoga',
    'cuyana': 'https://www.tiktok.com/@cuyana',
    'cep': 'https://www.tiktok.com/@cep_compression',
    'cos-na': 'https://www.tiktok.com/@cosstores',
    'csb-crop-shop-boutique': 'https://www.tiktok.com/@cropshopboutique',
    'cabelas-redhead': 'https://www.tiktok.com/@cabelas',
    'calpak': 'https://www.tiktok.com/@calpak',
    'calvin-klein-na': 'https://www.tiktok.com/@calvinklein',
    'carbon38': 'https://www.tiktok.com/@carbon38',
    'carhartt-wip': 'https://www.tiktok.com/@carharttwip',
    'catbird': 'https://www.tiktok.com/@catbirdnyc',
    'cecilie-bahnsen': 'https://www.tiktok.com/@ceciliebahnsen',
    'champion-hanes': 'https://www.tiktok.com/@champion',
    'clarks-na': 'https://www.tiktok.com/@clarksshoes',
    'coach': 'https://www.tiktok.com/@coach',
    'compressport': 'https://www.tiktok.com/@compressport',
    'converse-nike': 'https://www.tiktok.com/@converse',
    'courreges': 'https://www.tiktok.com/@courreges',
    'craft-sportswear': 'https://www.tiktok.com/@craftsportswear',
    'crap-eyewear': 'https://www.tiktok.com/@crapeyewear',
    
    # D
    'dansko-na': 'https://www.tiktok.com/@dansko',
    'dansko': 'https://www.tiktok.com/@dansko',
    'daniel-wellington-na': 'https://www.tiktok.com/@danielwellington',
    'david-yurman': 'https://www.tiktok.com/@davidyurman',
    'dickies': 'https://www.tiktok.com/@dickies',
    'diadora-na': 'https://www.tiktok.com/@diadora',
    'diff-eyewear-na': 'https://www.tiktok.com/@diffeyewear',
    'dior-na': 'https://www.tiktok.com/@dior',
    'district-vision': 'https://www.tiktok.com/@districtvision',
    'dolce-gabbana-na': 'https://www.tiktok.com/@dolcegabbana',
    'dr-martens-na': 'https://www.tiktok.com/@drmartens',
    'drake-waterfowl': 'https://www.tiktok.com/@drakewaterfowl',
    'duckfeet-na': 'https://www.tiktok.com/@duckfeet',
    'duluth-trading': 'https://www.tiktok.com/@duluthtrading',
    'dyson-na': 'https://www.tiktok.com/@dyson',
    'dkny-na': 'https://www.tiktok.com/@dkny',
    'dsw-designer-shoe-warehouse': 'https://www.tiktok.com/@dsw',
    'dagne-dover': 'https://www.tiktok.com/@dagnedover',
    'daily-drills': 'https://www.tiktok.com/@dailydrills',
    'danner': 'https://www.tiktok.com/@danner',
    'darn-tough': 'https://www.tiktok.com/@darntough',
    'deuter': 'https://www.tiktok.com/@deuter',
    'dickies-vf': 'https://www.tiktok.com/@dickies',
    'dickies-na': 'https://www.tiktok.com/@dickies',
    'diff-eyewear': 'https://www.tiktok.com/@diffeyewear',
    'doyoueven': 'https://www.tiktok.com/@doyoueven',
    'duer': 'https://www.tiktok.com/@duer',
    'duluth-pack': 'https://www.tiktok.com/@duluthpack',
    'duluth-trading-co': 'https://www.tiktok.com/@duluthtrading',
    
    # E
    'ecco-na': 'https://www.tiktok.com/@ecco',
    'eddie-bauer': 'https://www.tiktok.com/@eddiebauer',
    'eileen-fisher': 'https://www.tiktok.com/@eileenfisher',
    'evereve': 'https://www.tiktok.com/@evereve',
    'everlane': 'https://www.tiktok.com/@everlane',
    'express': 'https://www.tiktok.com/@express',
    'eberjey': 'https://www.tiktok.com/@eberjey',
    'eddie-bauer-na': 'https://www.tiktok.com/@eddiebauer',
    'eloquii': 'https://www.tiktok.com/@eloquii',
    'express-na': 'https://www.tiktok.com/@express',
    
    # F
    'faherty': 'https://www.tiktok.com/@fahertybrand',
    'fear-of-god': 'https://www.tiktok.com/@fearofgod',
    'feetures': 'https://www.tiktok.com/@feetures',
    'fendi-na': 'https://www.tiktok.com/@fendi',
    'ferragamo-na': 'https://www.tiktok.com/@ferragamo',
    'filson': 'https://www.tiktok.com/@filson1897',
    'filippa-k-na': 'https://www.tiktok.com/@filippak',
    'fossil-na': 'https://www.tiktok.com/@fossil',
    'fp-movement': 'https://www.tiktok.com/@fpmovement',
    'frank-and-eileen': 'https://www.tiktok.com/@frankandeileen',
    'free-fly': 'https://www.tiktok.com/@freeflyapparel',
    'fabletics-na': 'https://www.tiktok.com/@fabletics',
    'fear-of-god-essentials': 'https://www.tiktok.com/@fearofgod',
    'fila-na': 'https://www.tiktok.com/@fila',
    'fjallraven-na': 'https://www.tiktok.com/@fjallraven',
    'fleo': 'https://www.tiktok.com/@fleo',
    'flint-and-tinder': 'https://www.tiktok.com/@flintandtinder',
    'frankies-bikinis': 'https://www.tiktok.com/@frankiesbikinis',
    'free-people-na': 'https://www.tiktok.com/@freepeople',
    
    # G
    'g-shock-na': 'https://www.tiktok.com/@gshock',
    'g-star-na': 'https://www.tiktok.com/@gstarraw',
    'gant': 'https://www.tiktok.com/@gant',
    'gap': 'https://www.tiktok.com/@gap',
    'garmin-na': 'https://www.tiktok.com/@garmin',
    'givenchy-na': 'https://www.tiktok.com/@givenchy',
    'good-american': 'https://www.tiktok.com/@goodamerican',
    'gorjana': 'https://www.tiktok.com/@gorjana',
    'greats': 'https://www.tiktok.com/@greats',
    'greyson-clothiers': 'https://www.tiktok.com/@greysonclothiers',
    'gucci-na': 'https://www.tiktok.com/@gucci',
    'gymshark-na': 'https://www.tiktok.com/@gymshark',
    'ganni-na': 'https://www.tiktok.com/@ganni',
    'gap-na': 'https://www.tiktok.com/@gap',
    'girlfriend-collective': 'https://www.tiktok.com/@girlfriendcollective',
    'goldwin-na': 'https://www.tiktok.com/@goldwin',
    'goyard': 'https://www.tiktok.com/@goyard',
    'gramicci-na': 'https://www.tiktok.com/@gramicci',
    'gregory': 'https://www.tiktok.com/@gregorypacks',
    'guess': 'https://www.tiktok.com/@guess',
    'gymboree-na': 'https://www.tiktok.com/@gymboree',
    
    # H
    'hanna-andersson': 'https://www.tiktok.com/@hannaandersson',
    'head-na': 'https://www.tiktok.com/@head_tennis',
    'helly-hansen': 'https://www.tiktok.com/@hellyhansen',
    'hermes-na': 'https://www.tiktok.com/@hermes',
    'herschel': 'https://www.tiktok.com/@herschel',
    'herschel-supply-co': 'https://www.tiktok.com/@herschel',
    'hoka-na': 'https://www.tiktok.com/@hoka',
    'huckberry': 'https://www.tiktok.com/@huckberry',
    'hunter': 'https://www.tiktok.com/@hunterboots',
    'hydro-flask': 'https://www.tiktok.com/@hydroflask',
    'hm-na': 'https://www.tiktok.com/@hm',
    'haglofs': 'https://www.tiktok.com/@haglofs',
    'head': 'https://www.tiktok.com/@head_tennis',
    'heydude': 'https://www.tiktok.com/@heydude',
    'hollister': 'https://www.tiktok.com/@hollister',
    'hudson-jeans': 'https://www.tiktok.com/@hudsonjeans',
    
    # I
    'icebreaker-vf': 'https://www.tiktok.com/@icebreakernz',
    'imogene-and-willie': 'https://www.tiktok.com/@imogeneandwillie',
    'isabel-marant-na': 'https://www.tiktok.com/@isabelmarant',
    'injinji': 'https://www.tiktok.com/@injinji',
    'italic': 'https://www.tiktok.com/@italic',
    
    # J
    'jack-wolfskin-na': 'https://www.tiktok.com/@jackwolfskin',
    'janji': 'https://www.tiktok.com/@runjanji',
    'jenny-bird': 'https://www.tiktok.com/@jennybird',
    'joah-brown': 'https://www.tiktok.com/@joahbrown',
    'jockey': 'https://www.tiktok.com/@jockey',
    'john-elliott': 'https://www.tiktok.com/@johnelliott',
    'johnnie-o': 'https://www.tiktok.com/@johnnieo',
    'jordan-brand-nike': 'https://www.tiktok.com/@jordan',
    'jcrew': 'https://www.tiktok.com/@jcrew',
    'jcrew-na': 'https://www.tiktok.com/@jcrew',
    'jaanuu': 'https://www.tiktok.com/@jaanuu',
    'jacquemus-na': 'https://www.tiktok.com/@jacquemus',
    'jansport': 'https://www.tiktok.com/@jansport',
    'janie-and-jack-na': 'https://www.tiktok.com/@janieandjack',
    'jjjjound': 'https://www.tiktok.com/@jjjjound',
    
    # K
    'kappa-na': 'https://www.tiktok.com/@kappa',
    'karhu-na': 'https://www.tiktok.com/@karhu',
    'kendra-scott': 'https://www.tiktok.com/@kendrascott',
    'kevins-catalog': 'https://www.tiktok.com/@kevinscatalog',
    'kiehls-na': 'https://www.tiktok.com/@kiehls',
    'koio': 'https://www.tiktok.com/@koio',
    'kuhl': 'https://www.tiktok.com/@kuhl',
    'kswiss-na': 'https://www.tiktok.com/@kswiss',
    'keen': 'https://www.tiktok.com/@keen',
    'kate-spade': 'https://www.tiktok.com/@katespade',
    'kate-spade-na': 'https://www.tiktok.com/@katespade',
    'kavu': 'https://www.tiktok.com/@kavu',
    'keds': 'https://www.tiktok.com/@keds',
    'kickee-pants': 'https://www.tiktok.com/@kickeepants',
    'kit-and-ace': 'https://www.tiktok.com/@kitandace',
    'knix': 'https://www.tiktok.com/@knix',
    'krost': 'https://www.tiktok.com/@krost',
    'kuru-footwear': 'https://www.tiktok.com/@kurufootwear',
    'kyte-baby': 'https://www.tiktok.com/@kytebaby',
    
    # L
    'lacoste-na': 'https://www.tiktok.com/@lacoste',
    'lafayette-148': 'https://www.tiktok.com/@lafayette148',
    'lakers': 'https://www.tiktok.com/@lakers',
    'lanvin-na': 'https://www.tiktok.com/@lanvin',
    'lele-sadoughi': 'https://www.tiktok.com/@lelesadoughi',
    'lesportsac': 'https://www.tiktok.com/@lesportsac',
    'levis-na': 'https://www.tiktok.com/@levis',
    'lindenle': 'https://www.tiktok.com/@lindenle',
    'll-bean-na': 'https://www.tiktok.com/@llbean',
    'lo-and-sons': 'https://www.tiktok.com/@loandsons',
    'loeffler-randall': 'https://www.tiktok.com/@loefflerrandall',
    'longchamp-na': 'https://www.tiktok.com/@longchamp',
    'loewe-na': 'https://www.tiktok.com/@loewe',
    'louis-vuitton-na': 'https://www.tiktok.com/@louisvuitton',
    'lowa-na': 'https://www.tiktok.com/@lowa',
    'lucky-brand': 'https://www.tiktok.com/@luckybrand',
    'lululemon-na': 'https://www.tiktok.com/@lululemon',
    'llbean-na': 'https://www.tiktok.com/@llbean',
    'lndr': 'https://www.tiktok.com/@lndr',
    'la-sportiva-na': 'https://www.tiktok.com/@lasportiva',
    'lee-na': 'https://www.tiktok.com/@lee',
    'left-on-friday': 'https://www.tiktok.com/@leftonfriday',
    'les-tien': 'https://www.tiktok.com/@lestien',
    'levi-strauss-co': 'https://www.tiktok.com/@levis',
    'little-sleepies': 'https://www.tiktok.com/@littlesleepies',
    'longchamp': 'https://www.tiktok.com/@longchamp',
    'loro-piana': 'https://www.tiktok.com/@loropiana',
    'loro-piana-na': 'https://www.tiktok.com/@loropiana',
    
    # M
    'm-gemi': 'https://www.tiktok.com/@mgemi',
    'mackage': 'https://www.tiktok.com/@mackage',
    'madewell': 'https://www.tiktok.com/@madewell',
    'mango-na': 'https://www.tiktok.com/@mango',
    'marimekko-na': 'https://www.tiktok.com/@marimekko',
    'marni-na': 'https://www.tiktok.com/@marni',
    'max-mara-na': 'https://www.tiktok.com/@maxmara',
    'mejuri': 'https://www.tiktok.com/@mejuri',
    'merrell': 'https://www.tiktok.com/@merrell',
    'miansai': 'https://www.tiktok.com/@miansai',
    'michael-kors-na': 'https://www.tiktok.com/@michaelkors',
    'microsoft-na': 'https://www.tiktok.com/@microsoft',
    'miumiu-na': 'https://www.tiktok.com/@miumiu',
    'mizuno-na': 'https://www.tiktok.com/@mizuno',
    'mizzen-main': 'https://www.tiktok.com/@mizzenandmain',
    'moleskine-na': 'https://www.tiktok.com/@moleskine',
    'moncler-na': 'https://www.tiktok.com/@moncler',
    'montbell-na': 'https://www.tiktok.com/@montbell',
    'montblanc-na': 'https://www.tiktok.com/@montblanc',
    'mott-and-bow': 'https://www.tiktok.com/@mottandbow',
    'mackage-na': 'https://www.tiktok.com/@mackage',
    'mgemi': 'https://www.tiktok.com/@mgemi',
    'mmlafleur': 'https://www.tiktok.com/@mmlafleur',
    'mate-the-label': 'https://www.tiktok.com/@matethelabel',
    'mvmt': 'https://www.tiktok.com/@mvmt',
    'mz-wallace': 'https://www.tiktok.com/@mzwallace',
    'maje-na': 'https://www.tiktok.com/@maje',
    'mammut-na': 'https://www.tiktok.com/@mammut',
    'mansur-gavriel': 'https://www.tiktok.com/@mansurgavriel',
    'marc-jacobs-na': 'https://www.tiktok.com/@marcjacobs',
    'margaux': 'https://www.tiktok.com/@margaux',
    'marine-layer': 'https://www.tiktok.com/@marinelayer',
    'max-mara': 'https://www.tiktok.com/@maxmara',
    'mcdavid': 'https://www.tiktok.com/@mcdavid',
    'meundies': 'https://www.tiktok.com/@meundies',
    'michael-kors': 'https://www.tiktok.com/@michaelkors',
    'mini-boden': 'https://www.tiktok.com/@miniboden',
    'ministry-of-supply': 'https://www.tiktok.com/@ministryofsupply',
    'missoma-na': 'https://www.tiktok.com/@missoma',
    'monday-swimwear': 'https://www.tiktok.com/@mondayswimwear',
    'monica-andy': 'https://www.tiktok.com/@monicaandy',
    'moose-knuckles': 'https://www.tiktok.com/@mooseknuckles',
    'mother-denim': 'https://www.tiktok.com/@motherdenim',
    'mott-bow': 'https://www.tiktok.com/@mottandbow',
    'mountain-equipment': 'https://www.tiktok.com/@mountainequipment',
    'mountain-hardwear': 'https://www.tiktok.com/@mountainhardwear',
    'moving-comfort-brooks': 'https://www.tiktok.com/@brooksrunning',
    'muck-boot': 'https://www.tiktok.com/@muckboot',
    'muscle-nation': 'https://www.tiktok.com/@musclenation',
    'myles-apparel': 'https://www.tiktok.com/@mylesapparel',
    
    # N
    'naadam': 'https://www.tiktok.com/@naadam',
    'naked-cashmere': 'https://www.tiktok.com/@nakedcashmere',
    'nanushka-na': 'https://www.tiktok.com/@nanushka',
    'new-balance-na': 'https://www.tiktok.com/@newbalance',
    'nike-na': 'https://www.tiktok.com/@nike',
    'nili-lotan': 'https://www.tiktok.com/@nililotan',
    'nixon': 'https://www.tiktok.com/@nixon',
    'nomatic': 'https://www.tiktok.com/@nomatic',
    'nordstrom-na': 'https://www.tiktok.com/@nordstrom',
    'norrona': 'https://www.tiktok.com/@norrona',
    'north-face-na': 'https://www.tiktok.com/@thenorthface',
    'nvgtn': 'https://www.tiktok.com/@nvgtn',
    'naturalizer': 'https://www.tiktok.com/@naturalizer',
    'negative-underwear': 'https://www.tiktok.com/@negativeunderwear',
    'new-era': 'https://www.tiktok.com/@neweracap',
    'nisolo': 'https://www.tiktok.com/@nisolo',
    'nobull': 'https://www.tiktok.com/@nobull',
    'north-face': 'https://www.tiktok.com/@thenorthface',
    
    # O
    'oakley': 'https://www.tiktok.com/@oakley',
    'off-white-na': 'https://www.tiktok.com/@offwhite',
    'olukai': 'https://www.tiktok.com/@olukai',
    'on-running-na': 'https://www.tiktok.com/@on',
    'oneill': 'https://www.tiktok.com/@oneill',
    'orvis': 'https://www.tiktok.com/@orvis',
    'oscar-de-la-renta-na': 'https://www.tiktok.com/@oscardelarenta',
    'our-legacy-na': 'https://www.tiktok.com/@ourlegacy',
    'outdoor-research': 'https://www.tiktok.com/@outdoorresearch',
    'outerknown': 'https://www.tiktok.com/@outerknown',
    'odlo': 'https://www.tiktok.com/@odlo',
    'oiselle': 'https://www.tiktok.com/@oiselle',
    'old-navy': 'https://www.tiktok.com/@oldnavy',
    'old-navy-active': 'https://www.tiktok.com/@oldnavy',
    'oliver-cabell': 'https://www.tiktok.com/@olivercabell',
    'on-na': 'https://www.tiktok.com/@on',
    'oofos': 'https://www.tiktok.com/@oofos',
    'osprey': 'https://www.tiktok.com/@osprey',
    
    # P
    'paige': 'https://www.tiktok.com/@paige',
    'pandora': 'https://www.tiktok.com/@pandora',
    'parachute': 'https://www.tiktok.com/@parachutehome',
    'pas-normal-studios': 'https://www.tiktok.com/@pasnormalstudios',
    'patagonia-na': 'https://www.tiktok.com/@patagonia',
    'patou-na': 'https://www.tiktok.com/@patou',
    'pearle-izumi': 'https://www.tiktok.com/@pearlizumi',
    'pendleton': 'https://www.tiktok.com/@pendletonwm',
    'polo-ralph-lauren-na': 'https://www.tiktok.com/@poloralphlauren',
    'polartec': 'https://www.tiktok.com/@polartec',
    'prada-na': 'https://www.tiktok.com/@prada',
    'primary': 'https://www.tiktok.com/@primary',
    'proenza-schouler-na': 'https://www.tiktok.com/@proenzaschouler',
    'public-rec': 'https://www.tiktok.com/@publicrec',
    'puma-na': 'https://www.tiktok.com/@puma',
    'pe-nation': 'https://www.tiktok.com/@penation',
    'pact': 'https://www.tiktok.com/@pact',
    'paige-na': 'https://www.tiktok.com/@paige',
    'parachute-home': 'https://www.tiktok.com/@parachutehome',
    'paravel': 'https://www.tiktok.com/@paravel',
    'peak-design': 'https://www.tiktok.com/@peakdesign',
    'peak-performance-na': 'https://www.tiktok.com/@peakperformance',
    'peter-millar-na': 'https://www.tiktok.com/@petermillar',
    'polene': 'https://www.tiktok.com/@polene',
    'prana': 'https://www.tiktok.com/@prana',
    
    # Q
    'quay-na': 'https://www.tiktok.com/@quay',
    'quay': 'https://www.tiktok.com/@quay',
    'quince': 'https://www.tiktok.com/@quince',
    
    # R
    'rabbit': 'https://www.tiktok.com/@rabbit',
    'rag-and-bone-na': 'https://www.tiktok.com/@ragandbone',
    'rains-na': 'https://www.tiktok.com/@rains',
    'ralph-lauren-na': 'https://www.tiktok.com/@ralphlauren',
    'rapha-na': 'https://www.tiktok.com/@rapha',
    'rebecca-minkoff-na': 'https://www.tiktok.com/@rebeccaminkoff',
    'red-wing': 'https://www.tiktok.com/@redwing',
    'reebok-na': 'https://www.tiktok.com/@reebok',
    'reformation-na': 'https://www.tiktok.com/@reformation',
    'reigning-champ': 'https://www.tiktok.com/@reigningchamp',
    'rei-co-op': 'https://www.tiktok.com/@rei',
    'rhone': 'https://www.tiktok.com/@rhone',
    'rimowa-na': 'https://www.tiktok.com/@rimowa',
    'roger-federer-na': 'https://www.tiktok.com/@rogerfederer',
    'rolex-na': 'https://www.tiktok.com/@rolex',
    'rossignol-na': 'https://www.tiktok.com/@rossignol',
    'rothys': 'https://www.tiktok.com/@rothys',
    'rowenta-na': 'https://www.tiktok.com/@rowenta',
    'rab': 'https://www.tiktok.com/@rab',
    'rag-bone-na': 'https://www.tiktok.com/@ragandbone',
    'reebok': 'https://www.tiktok.com/@reebok',
    'reef': 'https://www.tiktok.com/@reef',
    'relwen': 'https://www.tiktok.com/@relwen',
    'rent-the-runway': 'https://www.tiktok.com/@renttherunway',
    'roa-hiking': 'https://www.tiktok.com/@roahiking',
    'roark': 'https://www.tiktok.com/@roark',
    'rotate': 'https://www.tiktok.com/@rotate',
    'royal-robbins': 'https://www.tiktok.com/@royalrobbins',
    'russell-athletic-na': 'https://www.tiktok.com/@russellathletic',
    'ryderwear': 'https://www.tiktok.com/@ryderwear',
    'rylee-cru': 'https://www.tiktok.com/@ryleeandcru',
    
    # S
    'saint-laurent-na': 'https://www.tiktok.com/@ysl',
    'salomon-na': 'https://www.tiktok.com/@salomon',
    'salvatore-ferragamo-na': 'https://www.tiktok.com/@ferragamo',
    'samsonite-na': 'https://www.tiktok.com/@samsonite',
    'saucony': 'https://www.tiktok.com/@saucony',
    'scarpa-na': 'https://www.tiktok.com/@scarpa',
    'seiko-na': 'https://www.tiktok.com/@seiko',
    'shinola': 'https://www.tiktok.com/@shinola',
    'shock-absorber-na': 'https://www.tiktok.com/@shockabsorber',
    'simply-southern': 'https://www.tiktok.com/@simplysouthern',
    'skechers-na': 'https://www.tiktok.com/@skechers',
    'skims': 'https://www.tiktok.com/@skims',
    'smartwool': 'https://www.tiktok.com/@smartwool',
    'sorel': 'https://www.tiktok.com/@sorel',
    'spanx': 'https://www.tiktok.com/@spanx',
    'staud': 'https://www.tiktok.com/@staud',
    'steve-madden-na': 'https://www.tiktok.com/@stevemadden',
    'stine-goya': 'https://www.tiktok.com/@stinegoya',
    'stio': 'https://www.tiktok.com/@stio',
    'stuart-weitzman-na': 'https://www.tiktok.com/@stuartweitzman',
    'stutterheim-na': 'https://www.tiktok.com/@stutterheim',
    'summersalt': 'https://www.tiktok.com/@summersalt',
    'sunspel': 'https://www.tiktok.com/@sunspel',
    'sweaty-betty': 'https://www.tiktok.com/@sweatybetty',
    'salming': 'https://www.tiktok.com/@salming',
    'sam-edelman': 'https://www.tiktok.com/@samedelman',
    'sam-edelman-na': 'https://www.tiktok.com/@samedelman',
    'sandro-na': 'https://www.tiktok.com/@sandro',
    'sanuk-deckers': 'https://www.tiktok.com/@sanuk',
    'sarah-flint': 'https://www.tiktok.com/@sarahflint',
    'satisfy-running': 'https://www.tiktok.com/@satisfyrunning',
    'self-portrait': 'https://www.tiktok.com/@selfportrait',
    'senreve': 'https://www.tiktok.com/@senreve',
    'set-active': 'https://www.tiktok.com/@setactive',
    'sherpa-adventure-gear': 'https://www.tiktok.com/@sherpaadventure',
    'shock-doctor': 'https://www.tiktok.com/@shockdoctor',
    'skagen-na': 'https://www.tiktok.com/@skagen',
    'skins': 'https://www.tiktok.com/@skins',
    'solid-and-striped': 'https://www.tiktok.com/@solidandstriped',
    'spalding': 'https://www.tiktok.com/@spalding',
    'spalding-na': 'https://www.tiktok.com/@spalding',
    'sperry': 'https://www.tiktok.com/@sperry',
    'state-bags': 'https://www.tiktok.com/@statebags',
    'steve-madden': 'https://www.tiktok.com/@stevemadden',
    'stone-island-na': 'https://www.tiktok.com/@stoneisland',
    
    # T
    'tacs-nato': 'https://www.tiktok.com/@tacsnato',
    'taft': 'https://www.tiktok.com/@taft',
    'tag-heuer-na': 'https://www.tiktok.com/@tagheuer',
    'taylor-stitch': 'https://www.tiktok.com/@taylorstitch',
    'teva': 'https://www.tiktok.com/@teva',
    'theory-na': 'https://www.tiktok.com/@theory',
    'thom-browne-na': 'https://www.tiktok.com/@thombrowne',
    'thursday-boot': 'https://www.tiktok.com/@thursdayboots',
    'tiffany-na': 'https://www.tiktok.com/@tiffanyandco',
    'timex-na': 'https://www.tiktok.com/@timex',
    'todd-snyder': 'https://www.tiktok.com/@toddsnyder',
    'tom-ford-na': 'https://www.tiktok.com/@tomford',
    'tommy-hilfiger-na': 'https://www.tiktok.com/@tommyhilfiger',
    'topo-athletic': 'https://www.tiktok.com/@topoathletic',
    'tory-burch-na': 'https://www.tiktok.com/@toryburch',
    'toteme': 'https://www.tiktok.com/@toteme',
    'tracksmith': 'https://www.tiktok.com/@tracksmith',
    'travismathew-na': 'https://www.tiktok.com/@travismathew',
    'tumi-na': 'https://www.tiktok.com/@tumi',
    'turtleson': 'https://www.tiktok.com/@turtleson',
    'two-thirds': 'https://www.tiktok.com/@twothirds',
    'tala': 'https://www.tiktok.com/@tala',
    'target-all-in-motion': 'https://www.tiktok.com/@target',
    'tea-collection': 'https://www.tiktok.com/@teacollection',
    'tentree': 'https://www.tiktok.com/@tentree',
    'teva-deckers': 'https://www.tiktok.com/@teva',
    'the-honest-company': 'https://www.tiktok.com/@thehonestcompany',
    'the-north-face-na': 'https://www.tiktok.com/@thenorthface',
    'the-row': 'https://www.tiktok.com/@therow',
    'theory': 'https://www.tiktok.com/@theory',
    'thursday-boots': 'https://www.tiktok.com/@thursdayboots',
    'timberland-na': 'https://www.tiktok.com/@timberland',
    'timbuk2': 'https://www.tiktok.com/@timbuk2',
    'tods-na': 'https://www.tiktok.com/@tods',
    'tommy-john': 'https://www.tiktok.com/@tommyjohn',
    'toms': 'https://www.tiktok.com/@toms',
    'topo-designs': 'https://www.tiktok.com/@topodesigns',
    'torrid': 'https://www.tiktok.com/@torrid',
    'tory-sport': 'https://www.tiktok.com/@torysport',
    'tradlands': 'https://www.tiktok.com/@tradlands',
    'tumi': 'https://www.tiktok.com/@tumi',
    
    # U
    'ugg-na': 'https://www.tiktok.com/@ugg',
    'ulla-johnson-na': 'https://www.tiktok.com/@ullajohnson',
    'under-armour-na': 'https://www.tiktok.com/@underarmour',
    'uniqlo-na': 'https://www.tiktok.com/@uniqlo',
    'united-by-blue': 'https://www.tiktok.com/@unitedbyblue',
    'ugg-deckers': 'https://www.tiktok.com/@ugg',
    'universal-standard': 'https://www.tiktok.com/@universalstandard',
    'untuckit': 'https://www.tiktok.com/@untuckit',
    'urban-outfitters-na': 'https://www.tiktok.com/@urbanoutfitters',
    
    # V
    'valentino-na': 'https://www.tiktok.com/@valentino',
    'vans-na': 'https://www.tiktok.com/@vans',
    'veja': 'https://www.tiktok.com/@veja',
    'venroy': 'https://www.tiktok.com/@venroy',
    'vera-bradley': 'https://www.tiktok.com/@verabradley',
    'vessi': 'https://www.tiktok.com/@vessi',
    'victorias-secret': 'https://www.tiktok.com/@victoriassecret',
    'vince': 'https://www.tiktok.com/@vince',
    'vionic-na': 'https://www.tiktok.com/@vionic',
    'vitruvi': 'https://www.tiktok.com/@vitruvi',
    'vivaia': 'https://www.tiktok.com/@vivaia',
    'vuori': 'https://www.tiktok.com/@vuori',
    'veja-na': 'https://www.tiktok.com/@veja',
    'vans-vf': 'https://www.tiktok.com/@vans',
    'varley': 'https://www.tiktok.com/@varley',
    'versace-na': 'https://www.tiktok.com/@versace',
    'vetements': 'https://www.tiktok.com/@vetements',
    'vince-na': 'https://www.tiktok.com/@vince',
    'vionic': 'https://www.tiktok.com/@vionic',
    
    # W
    'warby-parker': 'https://www.tiktok.com/@warbyparker',
    'wilsons-leather': 'https://www.tiktok.com/@wilsonsleather',
    'wilson-na': 'https://www.tiktok.com/@wilson',
    'wolford-na': 'https://www.tiktok.com/@wolford',
    'woolrich': 'https://www.tiktok.com/@woolrich',
    'western-rise': 'https://www.tiktok.com/@westernrise',
    'wilson': 'https://www.tiktok.com/@wilson',
    'wolven': 'https://www.tiktok.com/@wolven',
    'wrangler-na': 'https://www.tiktok.com/@wrangler',
    
    # X
    'x-bionic': 'https://www.tiktok.com/@xbionic',
    
    # Y
    'yeti': 'https://www.tiktok.com/@yeti',
    'year-of-ours': 'https://www.tiktok.com/@yearofours',
    'yeezy-adidas': 'https://www.tiktok.com/@yeezy',
    
    # Z
    'zara-na': 'https://www.tiktok.com/@zara',
    'zegna-na': 'https://www.tiktok.com/@zegna',
    'zippity': 'https://www.tiktok.com/@zippity',
    'zegna': 'https://www.tiktok.com/@zegna',
}

def main():
    conn = sqlite3.connect(DB_PATH)
    conn.execute("PRAGMA journal_mode=WAL")
    cursor = conn.cursor()
    
    updated = 0
    not_found = []
    
    for slug, url in tiktok_map.items():
        cursor.execute(
            'UPDATE brands SET tiktok_url = ? WHERE slug = ? AND (tiktok_url IS NULL OR tiktok_url = "")',
            (url, slug)
        )
        if cursor.rowcount > 0:
            updated += 1
        else:
            not_found.append(slug)
    
    conn.commit()
    
    cursor.execute('SELECT COUNT(*) FROM brands WHERE tiktok_url IS NOT NULL AND tiktok_url != ""')
    has = cursor.fetchone()[0]
    cursor.execute('SELECT COUNT(*) FROM brands')
    total = cursor.fetchone()[0]
    
    print(f'=== TikTok URL 补充结果 ===')
    print(f'本次更新: {updated}')
    print(f'未匹配: {len(not_found)}')
    print(f'当前覆盖: {has}/{total} ({has*100//total}%)')
    
    if not_found:
        print(f'\n未匹配品牌:')
        for s in not_found:
            print(f'  {s}')
    
    conn.close()

if __name__ == '__main__':
    main()
