#!/usr/bin/env python3
"""
批量修复：英文描述→中文、补充母公司、扩展社媒链接
"""

import sqlite3
import re
from pathlib import Path

DB_PATH = Path(__file__).parent.parent / "data" / "competitive_research.db"


# ============================================================
# 1. 英文描述 → 中文翻译
# ============================================================
DESC_TRANSLATIONS = {
    'Off-White': 'Off-White 由 Virgil Abloh 于2012年在米兰创立，是连接街头文化与高级时装的标志性品牌。以斜条纹Logo、引号设计和工业风美学闻名，现属 LVMH 集团。',
    'Vetements': 'Vetements 由 Demna Gvasalia 于2014年在苏黎世创立，以前卫 oversized 剪裁、解构主义设计和对消费文化的讽刺著称，是当代最具颠覆性的奢侈品牌之一。',
    'Ami Paris': 'Ami Paris 由 Alexandre Mattiussi 于2011年在巴黎创立，以轻松优雅的男装和标志性爱心Logo闻名。品牌融合法式精致与都市休闲，是当代巴黎风格的代表。',
    'Marine Serre': 'Marine Serre 由同名设计师于2017年在巴黎创立，以新月Logo、升级再造面料和未来主义设计闻名。品牌将可持续理念与高级时装融合，是新生代设计师中最具影响力的品牌之一。',
    'Coperni': 'Coperni 由 Sébastien Meyer 和 Arnaud Vaillant 于2013年在巴黎创立，以科技感设计、3D打印和标志性喷漆连衣裙闻名。品牌融合时尚与科技，是巴黎时装周最具话题性的新锐品牌。',
    'Courreges': 'Courrèges 由 André Courrèges 于1961年在巴黎创立，是太空时代时尚的先驱。以几何剪裁、迷你裙和未来主义设计闻名，2020年复兴后重新成为当代时尚的焦点。',
    'Sperry': 'Sperry 由 Paul Sperry 于1935年在美国创立，是船鞋的发明者。以标志性 Top-Sider 船鞋和航海风格闻名，是美国东海岸学院风的经典代表。',
    'Toms': 'Toms 由 Blake Mycoskie 于2006年在洛杉矶创立，以"One for One"买一捐一公益模式闻名。品牌从帆布鞋起家，已扩展至眼镜、咖啡等品类，是全球社会企业的标杆。',
    'Keds': 'Keds 由美国橡胶公司于1916年创立，是经典帆布运动鞋的鼻祖。以 Champion 帆布鞋闻名，深受 Marilyn Monroe 和 Audrey Hepburn 等明星喜爱，是美国休闲风格的象征。',
    'Naturalizer': 'Naturalizer 由美国 Brown Shoe Company 于1927年创立，以舒适科技和女性化设计著称。品牌主打 Contour+ 舒适技术，是美国女性舒适鞋履的领导品牌之一。',
    'Herschel': 'Herschel Supply Co. 由 Lyndon 和 Jamie Cormack 兄弟于2009年在加拿大温哥华创立。以经典双肩包和复古户外风格闻名，是全球最受欢迎的背包品牌之一。',
    'Miansai': 'Miansai 由 Michael Saiger 于2008年在迈阿密创立，以手工制作的男女珠宝、手表和皮具著称。品牌融合航海元素与当代设计，是美国独立配饰品牌的代表。',
    'David Yurman': 'David Yurman 由 David 和 Sybil Yurman 于1980年在纽约创立，以标志性 Cable 手镯设计闻名。品牌将雕塑艺术与珠宝工艺融合，是美国现代奢侈珠宝的代表。',
    'Pandora': 'Pandora 由 Per Enevoldsen 于1982年在丹麦哥本哈根创立，以可定制串珠手链闻名全球。品牌主打亲民奢侈定位，是全球销量最大的珠宝品牌之一。',
    'Alex and Ani': 'Alex and Ani 由 Carolyn Rafaelian 于2004年在美国罗德岛创立，以可扩展金属丝手镯和正能量符号设计闻名。品牌融合环保理念与个性化配饰。',
    'Gregory': 'Gregory 由 Wayne Gregory 于1977年在美国加州创立，以专业户外背包和人体工学背负系统闻名。品牌服务登山、徒步和旅行爱好者，是技术背包领域的标杆。',
    'Deuter': 'Deuter 由 Hans Deuter 于1898年在德国奥格斯堡创立，是欧洲最古老的背包品牌之一。以 Aircomfort 透气背负系统和专业户外背包闻名，服务登山者和户外爱好者。',
    'Sorel': 'Sorel 由 Kaufman Rubber Company 于1962年在加拿大创立，以经典冬靴和极寒天气鞋履闻名。品牌融合功能性与时尚设计，现属 Columbia Sportswear 旗下。',
    'Hunter': 'Hunter 由 Henry Lee Norris 于1856年在英国苏格兰创立，以经典 Wellington 雨靴闻名。品牌从皇室认证起家，已发展为涵盖鞋履、服饰和配件的英伦生活方式品牌。',
    'Bogs': 'Bogs 由 Combs家族于2002年在美国俄勒冈创立，以防水保暖靴和 Neo-Tech 技术著称。品牌服务户外工作者和家庭用户，是功能性雨靴领域的领先品牌。',
    'Muck Boot': 'Muck Boot 由 The Original Muck Boot Company 于1999年在美国创立，以100%防水、自保温靴鞋闻名。品牌源于英国传统惠灵顿靴，现为户外工作和狩猎场景的首选。',
    'Abercrombie & Fitch': 'Abercrombie & Fitch 由 David Abercrombie 于1892年在纽约创立，是美国经典休闲服饰品牌。以学院风、牛仔裤和标志性香水闻名，近年成功转型为当代时尚品牌。',
    'American Eagle': 'American Eagle Outfitters 由 Jerry Silverman 于1977年创立，是美国领先的青少年休闲服饰品牌。以牛仔裤、休闲装和 Aerie 内衣子品牌闻名，年营收约50亿美元。',
    'Banana Republic': 'Banana Republic 由 Mel 和 Patricia Ziegler 于1978年在旧金山创立，现属 Gap Inc.。品牌以旅行灵感、高端基本款和现代职业装闻名，是美式商务休闲的代表。',
    'Carhartt': 'Carhartt 由 Hamilton Carhartt 于1889年在底特律创立，是美国经典工装品牌。以耐用工装夹克、工装裤和 Duck 面料闻名，从工人阶级服饰进化为全球潮流文化符号。',
    'Champion': 'Champion 由 Feinbloom 兄弟于1919年在纽约创立，是美国经典运动服饰品牌。以 Reverse Weave 卫衣和运动装备闻名，从大学校园到街头潮流，跨越世纪的美国运动文化符号。',
    'Coach': 'Coach 由 Lillian 和 Miles Cahn 于1941年在纽约创立，是美国领先的轻奢皮具品牌。以标志性手袋、皮革工艺和现代纽约风格闻名，现属 Tapestry 集团。',
    'Columbia Sportswear': 'Columbia Sportswear 由 Paul Lamfrom 于1938年在俄勒冈创立，是全球领先的户外运动品牌。以 Omni-Heat 热反射技术和多功能户外装备闻名，年营收约35亿美元。',
    'Dickies': 'Dickies 由 C.N. Williamson 和 E.E. Dickie 于1922年在德克萨斯创立，是美国经典工装品牌。以874工装裤和耐用工装闻名，从蓝领工作服进化为滑板和街头文化标志。',
    'Eddie Bauer': 'Eddie Bauer 由同名创始人于1920年在西雅图创立，是美国经典户外品牌。以首创羽绒夹克和探险精神闻名，从南极探险到日常户外，品牌历史跨越百年。',
    'Gap': 'Gap 由 Donald 和 Doris Fisher 于1969年在旧金山创立，是全球最大的服装零售商之一。以经典牛仔裤、基础款和美式休闲风格闻名，旗下拥有 Old Navy、Banana Republic 等品牌。',
    'Guess': 'Guess 由 Marciano 兄弟于1981年在洛杉矶创立，以性感牛仔、标志性三角Logo和80年代广告美学闻名。品牌融合欧洲时尚与美国风格，是全球知名的生活方式品牌。',
    'Hollister': 'Hollister 由 Abercrombie & Fitch 于2000年推出，以南加州冲浪文化为灵感。品牌定位青少年市场，以休闲服饰和标志性加州风格闻名。',
    'J.Crew': 'J.Crew 由 Mitchell Cinader 和 Saul Charles 于1983年在纽约创立，是美国经典时尚零售商。以学院风、高端基本款和标志性羊绒衫闻名，被誉为"美国中产的衣橱"。',
    'Levi Strauss & Co.': "Levi Strauss & Co. 由 Levi Strauss 于1853年在旧金山创立，是牛仔裤的发明者和全球牛仔行业的领导者。以501牛仔裤和双马标闻名，年营收约60亿美元，是美式文化的全球象征。",
    'Michael Kors': 'Michael Kors 由同名设计师于1981年在纽约创立，是全球领先的轻奢品牌。以 Jet Set 风格、标志性手袋和手表闻名，现属 Capri Holdings 集团，年营收约35亿美元。',
    'North Face': 'The North Face 由 Douglas Tompkins 于1966年在旧金山创立，是全球顶级户外品牌。以羽绒服、登山装备和探索精神闻名，现属 VF Corporation，年营收约36亿美元。',
    'Old Navy': 'Old Navy 由 Gap Inc. 于1994年推出，是美国最大的平价服饰品牌之一。以家庭服饰、趣味营销和高性价比著称，年营收约80亿美元。',
    'Patagonia': 'Patagonia 由 Yvon Chouinard 于1973年在加州创立，是全球最具影响力的可持续户外品牌。以环保使命、B Corp认证和"地球是我们唯一的股东"理念闻名，是商业向善的标杆。',
    'Polo Ralph Lauren': 'Polo Ralph Lauren 由 Ralph Lauren 于1967年在纽约创立，以马球Logo、常春藤风格和美式经典设计闻名。品牌代表美国上流社会生活方式，年营收约65亿美元。',
    'Reebok': 'Reebok 由 Joseph William Foster 于1958年在英国创立，是全球知名运动品牌。以 Classic Leather 和 Pump 科技闻名，现属 Authentic Brands Group，专注健身和生活方式领域。',
    'Timberland': 'Timberland 由 Nathan Swartz 于1952年在美国创立，以经典大黄靴闻名全球。品牌融合户外功能与街头风格，现属 VF Corporation。',
    'Tommy Hilfiger': 'Tommy Hilfiger 由同名设计师于1985年在美国创立，以红白蓝三色旗Logo和学院风闻名。品牌融合美式经典与流行文化，现属 PVH 集团，年营收约90亿美元。',
    'Vans': 'Vans 由 Paul Van Doren 于1966年在加州创立，是全球标志性滑板鞋品牌。以 Old Skool、Era 等经典鞋款和 Off the Wall 精神闻名，现属 VF Corporation。',
    "Victoria's Secret": "Victoria's Secret 由 Roy Raymond 于1977年在旧金山创立，是全球最大的女性内衣品牌。以年度时装秀和天使超模闻名，年营收约60亿美元。",
    'Zara': 'Zara 由 Amancio Ortega 于1975年在西班牙创立，是全球最大的快时尚品牌。以极速供应链、时尚反应和亲民价格闻名，母公司 Inditex 年营收约360亿欧元。',
    'DSW (Designer Shoe Warehouse)': 'DSW 由 Jay Schottenstein 于1991年在美国创立，是全美最大的品牌鞋履折扣零售商之一。以设计师品牌折扣、自助选购模式著称，母公司 Designer Brands Inc. 年营收约32亿美元。',
    'Kate Spade': 'Kate Spade 由 Kate 和 Andy Spade 于1993年在纽约创立，以俏皮设计、鲜艳色彩和现代女性气质闻名。现属 Tapestry 集团，涵盖手袋、服饰和配饰。',
    'Rent the Runway': 'Rent the Runway 由 Jennifer Hyman 和 Jennifer Fleiss 于2009年在纽约创立，是全球领先的时尚租赁平台。以设计师礼服和日常服饰订阅服务著称，改变了女性消费时尚的方式。',
    'The Honest Company': 'The Honest Company 由 Jessica Alba 于2011年在洛杉矶创立，以天然无毒的家居和母婴产品闻名。品牌涵盖纸尿裤、护肤品和清洁用品，2021年上市。',
    'YETI': 'YETI 由 Roy 和 Ryan Seiders 兄弟于2006年在德克萨斯创立，以高性能冷藏箱和户外饮具闻名。品牌从钓鱼冷藏箱起家，已发展为户外生活方式领域最具价值的品牌之一，年营收约17亿美元。',
}


# ============================================================
# 2. 母公司补充
# ============================================================
PARENT_UPDATES = {
    # LVMH 集团
    'Louis Vuitton': 'LVMH', 'Dior': 'LVMH', 'Fendi': 'LVMH', 'Givenchy': 'LVMH',
    'Celine': 'LVMH', 'Loewe': 'LVMH', 'Marc Jacobs': 'LVMH', 'Rimowa': 'LVMH',
    'Tiffany & Co.': 'LVMH', 'Bulgari': 'LVMH', 'Hublot': 'LVMH', 'TAG Heuer': 'LVMH',
    'Hennessy': 'LVMH', 'Moët & Chandon': 'LVMH', 'Sephora': 'LVMH',
    'Berluti': 'LVMH', 'Loro Piana': 'LVMH', 'Emilio Pucci': 'LVMH',
    'Kenzo': 'LVMH', 'Acqua di Parma': 'LVMH', 'Chaumet': 'LVMH',
    
    # Kering 集团
    'Gucci': 'Kering', 'Saint Laurent': 'Kering', 'Bottega Veneta': 'Kering',
    'Balenciaga': 'Kering', 'Alexander McQueen': 'Kering', 'Brioni': 'Kering',
    'Boucheron': 'Kering', 'Pomellato': 'Kering', 'Qeelin': 'Kering',
    
    # Richemont 集团
    'Cartier': 'Richemont', 'Van Cleef & Arpels': 'Richemont',
    'Chloé': 'Richemont', 'Montblanc': 'Richemont', 'Piaget': 'Richemont',
    'Jaeger-LeCoultre': 'Richemont', 'IWC Schaffhausen': 'Richemont',
    'Vacheron Constantin': 'Richemont', 'Panerai': 'Richemont',
    
    # PVH 集团
    'Calvin Klein': 'PVH Corp',
    
    # Capri Holdings
    'Versace': 'Capri Holdings', 'Jimmy Choo': 'Capri Holdings',
    
    # Tapestry
    'Stuart Weitzman': 'Tapestry, Inc.',
    
    # VF Corporation
    'Dickies': 'VF Corporation', 'Vans': 'VF Corporation',
    'Timberland': 'VF Corporation', 'The North Face': 'VF Corporation',
    'JanSport': 'VF Corporation', 'Smartwool': 'VF Corporation',
    'Icebreaker': 'VF Corporation', 'Altra': 'VF Corporation',
    'Eastpak': 'VF Corporation', 'Kipling': 'VF Corporation',
    
    # Deckers Brands
    'Hoka': 'Deckers Brands', 'UGG': 'Deckers Brands', 'Teva': 'Deckers Brands',
    'Sanuk': 'Deckers Brands',
    
    # Authentic Brands Group
    'Reebok': 'Authentic Brands Group', 'Forever 21': 'Authentic Brands Group',
    'Brooks Brothers': 'Authentic Brands Group', 'Aeropostale': 'Authentic Brands Group',
    'Eddie Bauer': 'Authentic Brands Group', 'Nautica': 'Authentic Brands Group',
    'Nine West': 'Authentic Brands Group', 'Juicy Couture': 'Authentic Brands Group',
    'Barneys New York': 'Authentic Brands Group',
    
    # Wolverine Worldwide
    'Merrell': 'Wolverine Worldwide', 'Sperry': 'Wolverine Worldwide',
    'Keds': 'Wolverine Worldwide', 'Saucony': 'Wolverine Worldwide',
    'Hush Puppies': 'Wolverine Worldwide',
    
    # HanesBrands
    'Champion': 'HanesBrands', 'Maidenform': 'HanesBrands',
    'Bali': 'HanesBrands', 'Playtex': 'HanesBrands',
    
    # Adidas
    'Reebok (classic)': 'Adidas (2005-2021), now Authentic Brands Group',
    
    # Levi Strauss
    'Dockers': 'Levi Strauss & Co.', 'Beyond Yoga': 'Levi Strauss & Co.',
    
    # Kontoor Brands (从VF Corp分拆)
    'Wrangler': 'Kontoor Brands', 'Lee': 'Kontoor Brands',
    
    # 更多独立品牌
    'Mango': 'Mango (私营家族企业)',
    'Mango (北美)': 'Mango (私营家族企业)',
    'COS': 'H&M Group',
    'COS (北美)': 'H&M Group',
    '& Other Stories': 'H&M Group',
    '& Other Stories (北美)': 'H&M Group',
    'Arket': 'H&M Group',
    'Monki': 'H&M Group',
    'Weekday': 'H&M Group',
    'Massimo Dutti': 'Inditex',
    'Bershka': 'Inditex',
    'Pull&Bear': 'Inditex',
    'Stradivarius': 'Inditex',
    'Oysho': 'Inditex',
    'Zara Home': 'Inditex',
    'Uterqüe': 'Inditex',
    'Sandro': 'SMCP Group',
    'Maje': 'SMCP Group',
    'Claudie Pierlot': 'SMCP Group',
    'DeMellier': 'DeMellier (独立品牌)',
    'Senreve': 'Senreve (独立品牌)',
    'Paravel': 'Paravel (独立品牌)',
    'Cuyana': 'Cuyana (独立品牌)',
    'Dagne Dover': 'Dagne Dover (独立品牌)',
    'MZ Wallace': 'MZ Wallace (独立品牌)',
    'Away': 'Away (独立品牌)',
    'Quince': 'Quince (独立品牌)',
    'Naadam': 'Naadam (独立品牌)',
    'Bombas': 'Bombas (独立品牌)',
    'Mack Weldon': 'Mack Weldon (独立品牌)',
    'Rhone': 'Rhone (独立品牌)',
    'Ten Thousand': 'Ten Thousand (独立品牌)',
    'Myles Apparel': 'Myles Apparel (独立品牌)',
    'Public Rec': 'Public Rec (独立品牌)',
    'Birddogs': 'Birddogs (独立品牌)',
    'Vuori': 'Vuori (独立品牌)',
    'Alo Yoga': 'Alo Yoga (独立品牌)',
    'Outdoor Voices': 'Outdoor Voices (独立品牌)',
    'Gymshark': 'Gymshark (独立品牌)',
    'Fabletics': 'Fabletics (TechStyle Fashion Group)',
    'Sweaty Betty': 'Sweaty Betty (Wolverine Worldwide)',
    'Varley': 'Varley (独立品牌)',
    'Satisfy Running': 'Satisfy Running (独立品牌)',
    'Tracksmith': 'Tracksmith (独立品牌)',
    'Bandit Running': 'Bandit Running (独立品牌)',
    'District Vision': 'District Vision (独立品牌)',
    'Janji': 'Janji (独立品牌)',
    'Ciele Athletics': 'Ciele Athletics (独立品牌)',
    'Rabbitt': 'Rabbitt (独立品牌)',
    'Path Projects': 'Path Projects (独立品牌)',
    'Wolaco': 'Wolaco (独立品牌)',
    'Nobull': 'Nobull (独立品牌)',
    'R.A.D.': 'R.A.D. (独立品牌)',
    'Nnormal': 'Nnormal (独立品牌)',
    'Speedland': 'Speedland (独立品牌)',
    'NordicTrack': 'iFIT Health & Fitness',
    'Peloton': 'Peloton Interactive, Inc.',
    'Mirror': 'Lululemon Athletica (已关闭)',
    'Hydrow': 'Hydrow, Inc.',
    'Tonal': 'Tonal Systems, Inc.',
    'Tempo': 'Tempo Interactive, Inc.',
    'FightCamp': 'FightCamp (独立品牌)',
    'GORUCK': 'GORUCK (独立品牌)',
    'Huckberry': 'Huckberry (独立品牌)',
    'Flint and Tinder': 'Huckberry (自有品牌)',
    'Proof': 'Huckberry (自有品牌)',
    'Wellen': 'Huckberry (自有品牌)',
    'Relwen': 'Relwen (独立品牌)',
    'Taylor Stitch': 'Taylor Stitch (独立品牌)',
    'Flint and Tinder (Huckberry)': 'Huckberry',
    'Buck Mason': 'Buck Mason (独立品牌)',
    'Jungmaven': 'Jungmaven (独立品牌)',
    'Marine Layer': 'Marine Layer (独立品牌)',
    'KÜHL': 'KÜHL (独立品牌)',
    'Roark': 'Roark (独立品牌)',
    'Topo Designs': 'Topo Designs (独立品牌)',
    'Cotopaxi': 'Cotopaxi (独立品牌)',
    'Nomatic': 'Nomatic (独立品牌)',
    'Timbuk2': 'Timbuk2 (独立品牌)',
    'Peak Design': 'Peak Design (独立品牌)',
    'Bellroy': 'Bellroy (独立品牌)',
    'AER': 'AER (独立品牌)',
    'Evergoods': 'Evergoods (独立品牌)',
    'Mystery Ranch': 'Yeti Holdings (2024年收购)',
    'Osprey': 'Helen of Troy Limited',
    'Gregory': 'Samsonite',
    'Deuter': 'Deuter Sport GmbH (私营家族企业)',
    'Thule': 'Thule Group AB (上市公司)',
    'Yakima': 'Yakima Products, Inc.',
    'Hydro Flask': 'Helen of Troy Limited',
    'Stanley': 'Stanley (PMI Worldwide)',
    'Owala': 'Owala (独立品牌)',
    'Corkcicle': 'Corkcicle (独立品牌)',
    'Brumate': 'Brumate (独立品牌)',
    'Simple Modern': 'Simple Modern (独立品牌)',
    'RTIC': 'RTIC Outdoors',
    'Orca': 'Orca (独立品牌)',
    'Pelican': 'Pelican Products, Inc.',
    'Engel': 'Engel Coolers (独立品牌)',
    'Grizzly': 'Grizzly Coolers (独立品牌)',
    'Kong': 'Kong Coolers (独立品牌)',
    'Bison': 'Bison Coolers (独立品牌)',
    'Fjällräven': 'Fenix Outdoor International AG',
    'Fjällräven (北美)': 'Fenix Outdoor International AG',
    'Haglöfs': 'ASICS Corporation',
    'Norrona': 'Norrona Sport AS (私营家族企业)',
    'Mammut': 'Telemos Capital (2021年收购)',
    'Mammut (北美)': 'Telemos Capital (2021年收购)',
    'Black Diamond': 'Black Diamond Equipment, Ltd. (Clarus Corp)',
    'Petzl': 'Petzl (私营家族企业)',
    'La Sportiva': 'La Sportiva (私营家族企业)',
    'Scarpa': 'Scarpa (私营家族企业)',
    'La Sportiva (北美)': 'La Sportiva (私营家族企业)',
    'Scarpa (北美)': 'Scarpa (私营家族企业)',
    'Mountain Hardwear': 'Columbia Sportswear',
    'prAna': 'Columbia Sportswear (2024年出售)',
    'Sorel': 'Columbia Sportswear',
    'Mountain Hardwear (Columbia)': 'Columbia Sportswear',
    'Helly Hansen': 'Canadian Tire Corporation',
    'Musto': 'Helly Hansen (Canadian Tire Corp)',
    'Mustang Survival': 'Mustang Survival (独立品牌)',
    'Grundéns': 'Grundéns (独立品牌)',
    'Gill Marine': 'Gill Marine (独立品牌)',
    'Zhik': 'Zhik (独立品牌)',
    'Rooster': 'Rooster Sailing (独立品牌)',
    'Xtratuf': 'Xtratuf (独立品牌)',
    'Muck Boot': 'Muck Boot (独立品牌)',
    'Bogs': 'Bogs (独立品牌)',
    'Kamik': 'Kamik (独立品牌)',
    'Cougar': 'Cougar Shoes (独立品牌)',
    'Pajar': 'Pajar (独立品牌)',
    'La Canadienne': 'La Canadienne (独立品牌)',
    'Aquatalia': 'Aquatalia (独立品牌)',
    'Blondo': 'Blondo (独立品牌)',
    'Blundstone': 'Blundstone (私营家族企业)',
    'Blundstone (北美)': 'Blundstone (私营家族企业)',
    'Dr. Martens': 'Dr. Martens plc (上市公司)',
    'Dr. Martens (北美)': 'Dr. Martens plc (上市公司)',
    'Clarks': 'Clarks (私营家族企业)',
    'Clarks (北美)': 'Clarks (私营家族企业)',
    'Birkenstock': 'Birkenstock Holding plc (上市公司)',
    'Birkenstock (北美)': 'Birkenstock Holding plc (上市公司)',
    'Birkenstock 1774': 'Birkenstock Holding plc',
    'Crocs': 'Crocs, Inc.',
    'Heydude': 'Crocs, Inc.',
    'Skechers': 'Skechers USA, Inc.',
    'Steve Madden': 'Steve Madden, Ltd.',
    'Aldo': 'Aldo Group (私营家族企业)',
    'Aldo (北美)': 'Aldo Group (私营家族企业)',
    'Call It Spring': 'Aldo Group',
    'Globo': 'Aldo Group',
    'DSW': 'Designer Brands Inc.',
    'DSW (Designer Shoe Warehouse)': 'Designer Brands Inc.',
    'Famous Footwear': 'Caleres, Inc.',
    'Caleres': 'Caleres, Inc.',
    'Sam Edelman': 'Caleres, Inc.',
    'Sam Edelman (北美)': 'Caleres, Inc.',
    'Naturalizer': 'Caleres, Inc.',
    'Vionic': 'Caleres, Inc.',
    'Vionic (北美)': 'Caleres, Inc.',
    'Franco Sarto': 'Caleres, Inc.',
    'Dr. Scholl\'s Shoes': 'Caleres, Inc.',
    'Rykä': 'Caleres, Inc.',
    'LifeStride': 'Caleres, Inc.',
    'Bzees': 'Caleres, Inc.',
    'Blowfish Malibu': 'Caleres, Inc.',
    'Circus by Sam Edelman': 'Caleres, Inc.',
    'Vince': 'Vince Holding Corp.',
    'Vince (北美)': 'Vince Holding Corp.',
    'Theory': 'Fast Retailing (优衣库母公司)',
    'Theory (北美)': 'Fast Retailing (优衣库母公司)',
    'Helmut Lang': 'Fast Retailing (优衣库母公司)',
    'J Brand': 'Fast Retailing (优衣库母公司)',
    'Comptoir des Cotonniers': 'Fast Retailing (优衣库母公司)',
    'Princesse tam.tam': 'Fast Retailing (优衣库母公司)',
    'Frame': 'Frame (独立品牌)',
    'AG Jeans': 'AG Adriano Goldschmied (独立品牌)',
    'AG Jeans (北美)': 'AG Adriano Goldschmied (独立品牌)',
    'Paige': 'PAIGE (独立品牌)',
    'Paige (北美)': 'PAIGE (独立品牌)',
    'Mother': 'MOTHER Denim (独立品牌)',
    'Citizens of Humanity': 'Citizens of Humanity (独立品牌)',
    'Rag & Bone': 'Rag & Bone (独立品牌)',
    'Rag & Bone (北美)': 'Rag & Bone (独立品牌)',
    '7 For All Mankind': 'Delta Galil Industries',
    '7 For All Mankind (北美)': 'Delta Galil Industries',
    'DL1961': 'DL1961 (独立品牌)',
    'Boyish': 'Boyish Jeans (独立品牌)',
    'Re/Done': 'Re/Done (独立品牌)',
    'Ética': 'Ética Denim (独立品牌)',
    'Outland Denim': 'Outland Denim (独立品牌)',
    'Ksubi': 'Ksubi (独立品牌)',
    'Abrand': 'Abrand Jeans (独立品牌)',
    'Rollas': 'Rollas Jeans (独立品牌)',
    'Neuw': 'Neuw Denim (独立品牌)',
    'Nudie Jeans': 'Nudie Jeans (独立品牌)',
    'G-Star RAW': 'G-Star RAW (独立品牌)',
    'Mavi': 'Mavi (上市公司)',
    'Silver Jeans Co.': 'Silver Jeans Co. (独立品牌)',
    'Lucky Brand': 'Authentic Brands Group / SPARC Group',
    'Joe\'s Jeans': 'Joe\'s Jeans (独立品牌)',
    'Hudson Jeans': 'Hudson Jeans (独立品牌)',
    'J Brand (Fast Retailing)': 'Fast Retailing',
    'Current/Elliott': 'Current/Elliott (独立品牌)',
    'Equipment': 'Equipment (独立品牌)',
    'Joie': 'Joie (独立品牌)',
    'A.L.C.': 'A.L.C. (独立品牌)',
    'Alice + Olivia': 'Alice + Olivia (独立品牌)',
    'Veronica Beard': 'Veronica Beard (独立品牌)',
    'Ulla Johnson': 'Ulla Johnson (独立品牌)',
    'Sea': 'Sea (独立品牌)',
    'LoveShackFancy': 'LoveShackFancy (独立品牌)',
    'Zimmermann': 'Zimmermann (Advent International投资)',
    'Reformation': 'Reformation (独立品牌)',
    'Rixo': 'Rixo (独立品牌)',
    'Rouje': 'Rouje (独立品牌)',
    'Sézane': 'Sézane (独立品牌)',
    'Ganni': 'Ganni (独立品牌)',
    'Ganni (北美)': 'Ganni (独立品牌)',
    'Staud': 'Staud (独立品牌)',
    'Khaite': 'Khaite (独立品牌)',
    'Toteme': 'Toteme (独立品牌)',
    'Acne Studios': 'Acne Studios (独立品牌)',
    'Isabel Marant': 'Isabel Marant (独立品牌)',
    'Jacquemus': 'Jacquemus (独立品牌)',
    'Jacquemus (北美)': 'Jacquemus (独立品牌)',
    'Ami': 'AMI Paris (独立品牌)',
    'Ami Paris': 'AMI Paris (独立品牌)',
    'A.P.C.': 'A.P.C. (独立品牌)',
    'Lemaire': 'Lemaire (独立品牌)',
    'Jil Sander': 'OTB Group (Only The Brave)',
    'Marni': 'OTB Group (Only The Brave)',
    'Diesel': 'OTB Group (Only The Brave)',
    'Maison Margiela': 'OTB Group (Only The Brave)',
    'Viktor & Rolf': 'OTB Group (Only The Brave)',
    'Amiri': 'Amiri (独立品牌)',
    'Rhude': 'Rhude (独立品牌)',
    'Fear of God': 'Fear of God (独立品牌)',
    'Aimé Leon Dore': "Aimé Leon Dore (LVMH投资)",
    'Kith': 'Kith (独立品牌)',
    'Stone Island': 'Moncler Group',
    'Stone Island (北美)': 'Moncler Group',
    'Palm Angels': 'Palm Angels (New Guards Group/Farfetch)',
    'Heron Preston': 'Heron Preston (独立品牌)',
    'A-Cold-Wall*': 'A-Cold-Wall* (独立品牌)',
    'Represent': 'Represent (独立品牌)',
    'Cole Buxton': 'Cole Buxton (独立品牌)',
    'Gallery Dept.': 'Gallery Dept. (独立品牌)',
    'Denim Tears': 'Denim Tears (独立品牌)',
    'Who Decides War': 'Who Decides War (独立品牌)',
    'Telfar': 'Telfar (独立品牌)',
    'Pyer Moss': 'Pyer Moss (独立品牌)',
    'Wales Bonner': 'Wales Bonner (独立品牌)',
    'Martine Rose': 'Martine Rose (独立品牌)',
    'Bianca Saunders': 'Bianca Saunders (独立品牌)',
    'Nicholas Daley': 'Nicholas Daley (独立品牌)',
    'Ahluwalia': 'Ahluwalia (独立品牌)',
    'Chopova Lowena': 'Chopova Lowena (独立品牌)',
    'Supriya Lele': 'Supriya Lele (独立品牌)',
    'Knwls': 'Knwls (独立品牌)',
    'Ottolinger': 'Ottolinger (独立品牌)',
    'Molly Goddard': 'Molly Goddard (独立品牌)',
    'Simone Rocha': 'Simone Rocha (独立品牌)',
    'Erdem': 'Erdem (独立品牌)',
    'Roksanda': 'Roksanda (独立品牌)',
    'Christopher Kane': 'Christopher Kane (独立品牌)',
    'Peter Do': 'Peter Do (独立品牌)',
    'Eckhaus Latta': 'Eckhaus Latta (独立品牌)',
    'Collina Strada': 'Collina Strada (独立品牌)',
    'Puppets and Puppets': 'Puppets and Puppets (独立品牌)',
    'Sandy Liang': 'Sandy Liang (独立品牌)',
    'Batsheva': 'Batsheva (独立品牌)',
    'Rachel Comey': 'Rachel Comey (独立品牌)',
    'Maryam Nassir Zadeh': 'Maryam Nassir Zadeh (独立品牌)',
    'Bode': 'Bode (独立品牌)',
    'Emily Bode': 'Bode (独立品牌)',
    'Connor McKnight': 'Connor McKnight (独立品牌)',
    'Head of State': 'Head of State (独立品牌)',
    'Willy Chavarria': 'Willy Chavarria (独立品牌)',
    'Luar': 'Luar (独立品牌)',
    'Palomo Spain': 'Palomo Spain (独立品牌)',
    'JW Anderson': 'LVMH (少数股权)',
    'Proenza Schouler': 'Proenza Schouler (独立品牌)',
    'Altuzarra': 'Altuzarra (独立品牌)',
    'Rosie Assoulin': 'Rosie Assoulin (独立品牌)',
    'Brock Collection': 'Brock Collection (独立品牌)',
    'Adam Lippes': 'Adam Lippes (独立品牌)',
    'Brandon Maxwell': 'Brandon Maxwell (独立品牌)',
    'Carolina Herrera': 'Puig',
    'Paco Rabanne': 'Puig',
    'Jean Paul Gaultier': 'Puig',
    'Nina Ricci': 'Puig',
    'Dries Van Noten': 'Puig',
    'Ann Demeulemeester': 'Ann Demeulemeester (独立品牌)',
    'Haider Ackermann': 'Haider Ackermann (独立品牌)',
    'Y/Project': 'Y/Project (独立品牌)',
    'Ludovic de Saint Sernin': 'Ludovic de Saint Sernin (独立品牌)',
    'Mugler': "L'Oréal (香水), 独立(时装)",
    'Lanvin': 'Lanvin Group (复星国际控股)',
    'Sergio Rossi': 'Lanvin Group (复星国际控股)',
    'St. John': 'Lanvin Group (复星国际控股)',
    'Wolford': 'Lanvin Group (复星国际控股)',
    'Caruso': 'Lanvin Group (复星国际控股)',
    'Victoria Beckham': 'Victoria Beckham (独立品牌)',
    'Stella McCartney': 'Stella McCartney (LVMH少数股权)',
    'Gabriela Hearst': 'Gabriela Hearst (独立品牌)',
    'Khaite (New York)': 'Khaite (独立品牌)',
    'The Row': 'The Row (Olsen姐妹独立品牌)',
    'Khaite (NYC)': 'Khaite (独立品牌)',
    'Pangaia': 'Pangaia (独立品牌)',
    'Everlane': 'Shein',
    'Cuyana (SF)': 'Cuyana (独立品牌)',
    'Naadam (NYC)': 'Naadam (独立品牌)',
    'Quince (SF)': 'Quince (独立品牌)',
    'Italic': 'Italic (独立品牌)',
    'M.Gemi': 'M.Gemi (独立品牌)',
    'Thursday Boots': 'Thursday Boots (独立品牌)',
    'Beckett Simonon': 'Beckett Simonon (独立品牌)',
    'Oliver Cabell': 'Oliver Cabell (独立品牌)',
    'Greats': 'Steve Madden (2019年收购)',
    'Koio': 'Koio (独立品牌)',
    'Axel Arigato': 'Axel Arigato (独立品牌)',
    'Eytys': 'Eytys (独立品牌)',
    'Veja': 'VEJA (独立品牌)',
    'VEJA (北美)': 'VEJA (独立品牌)',
    'Cariuma': 'Cariuma (独立品牌)',
    'Allbirds': 'Allbirds, Inc. (上市公司)',
    'Allbirds (北美)': 'Allbirds, Inc. (上市公司)',
    'Rothy\'s': "Rothy's (独立品牌)",
    'Vessi': 'Vessi (独立品牌)',
    'Native Shoes': 'Native Shoes (独立品牌)',
    'Heydude (Crocs)': 'Crocs, Inc.',
    'Oofos': 'Oofos (独立品牌)',
    'Hoka One One': 'Deckers Brands',
    'On': 'On Holding AG (上市公司)',
    'On (北美)': 'On Holding AG (上市公司)',
    'Salomon (北美)': 'Amer Sports (安踏体育)',
    'Arc\'teryx': 'Amer Sports (安踏体育)',
    'Arc\'teryx (北美)': 'Amer Sports (安踏体育)',
    'Atomic': 'Amer Sports (安踏体育)',
    'Wilson': 'Amer Sports (安踏体育)',
    'Wilson (北美)': 'Amer Sports (安踏体育)',
    'Louisville Slugger': 'Amer Sports (安踏体育)',
    'DeMarini': 'Amer Sports (安踏体育)',
    'EvoShield': 'Amer Sports (安踏体育)',
    'Peak Performance': 'Amer Sports (安踏体育)',
    'Peak Performance (北美)': 'Amer Sports (安踏体育)',
    'Armada': 'Amer Sports (安踏体育)',
    'ENVE Composites': 'Amer Sports (安踏体育)',
    'Suunto': 'Amer Sports (安踏体育)',
    'Precor': 'Amer Sports (安踏体育)',
    'Salomon': 'Amer Sports (安踏体育)',
    'Patagonia (private)': 'Patagonia, Inc. / Holdfast Collective',
    'New Balance': 'New Balance (私营)',
    'Brooks': 'Berkshire Hathaway (Brooks Running)',
    'ASICS': 'ASICS Corporation',
    'ASICS (北美)': 'ASICS Corporation',
    'Mizuno': 'Mizuno Corporation',
    'Mizuno (北美)': 'Mizuno Corporation',
    'Puma': 'Puma SE (Kering曾控股, 现Artémis/上市公司)',
    'Puma (北美)': 'Puma SE',
    'Under Armour': 'Under Armour, Inc. (上市公司)',
    'Lululemon': 'Lululemon Athletica, Inc. (上市公司)',
    'Athleta': 'Gap Inc.',
    'Fabletics (TechStyle)': 'TechStyle Fashion Group',
    'Outdoor Voices (独立)': 'Outdoor Voices (独立品牌)',
    'Girlfriend Collective': 'Girlfriend Collective (独立品牌)',
    'MATE the Label': 'MATE the Label (独立品牌)',
    'Pact': 'Pact (独立品牌)',
    'Organic Basics': 'Organic Basics (独立品牌)',
    'Harvest & Mill': 'Harvest & Mill (独立品牌)',
    'Groceries Apparel': 'Groceries Apparel (独立品牌)',
    'Christy Dawn': 'Christy Dawn (独立品牌)',
    'Doên': 'Doên (独立品牌)',
    'Dôen': 'Dôen (独立品牌)',
    'Sézane (Paris)': 'Sézane (独立品牌)',
    'Aritzia': 'Aritzia, Inc. (上市公司)',
    'Revolve': 'Revolve Group, Inc. (上市公司)',
    'FWRD': 'Revolve Group, Inc.',
    'Shopbop': 'Amazon',
    'Net-a-Porter': 'Richemont (已售予 Mytheresa)',
    'Mr Porter': 'Richemont (已售予 Mytheresa)',
    'Farfetch': 'Coupang (韩国电商)',
    'SSENSE': 'SSENSE (独立品牌)',
    'Matches Fashion': 'Matches (已破产)',
    'Mytheresa': 'Mytheresa (上市公司, 收购Net-a-Porter)',
    'Saks Fifth Avenue': "Saks Global (Hudson's Bay)",
    'Neiman Marcus': "Saks Global (Hudson's Bay)",
    'Bergdorf Goodman': "Saks Global (Hudson's Bay)",
    'Nordstrom': 'Nordstrom, Inc. (上市公司)',
    "Bloomingdale's": "Macy's, Inc.",
    "Macy's": "Macy's, Inc.",
    'Target': 'Target Corporation (上市公司)',
    'Walmart': 'Walmart Inc. (上市公司)',
    'Costco': 'Costco Wholesale Corporation (上市公司)',
    'Amazon': 'Amazon.com, Inc.',
    'Urban Outfitters': 'Urban Outfitters, Inc. (URBN)',
    'Anthropologie': 'Urban Outfitters, Inc. (URBN)',
    'Free People': 'Urban Outfitters, Inc. (URBN)',
    'Nuuly': 'Urban Outfitters, Inc. (URBN)',
    'FP Movement': 'Urban Outfitters, Inc. (URBN)',
    'BHLDN': 'Urban Outfitters, Inc. (URBN)',
    'Terrain': 'Urban Outfitters, Inc. (URBN)',
    'Madewell': 'J.Crew Group',
    'Everlane (SF)': 'Shein',
    'Buck Mason (LA)': 'Buck Mason (独立品牌)',
    'Taylor Stitch (SF)': 'Taylor Stitch (独立品牌)',
    'Marine Layer (SF)': 'Marine Layer (独立品牌)',
    'Faherty': 'Faherty (独立品牌)',
    'Rhone (CT)': 'Rhone (独立品牌)',
    'Mizzen+Main': 'Mizzen+Main (独立品牌)',
    'State and Liberty': 'State and Liberty (独立品牌)',
    'Untuckit': 'UNTUCKit (独立品牌)',
    'Bonobos': 'Express, Inc. / WHP Global',
    'Bonobos (北美)': 'Express, Inc. / WHP Global',
    'Peter Millar': 'Richemont',
    'Peter Millar (北美)': 'Richemont',
    'TravisMathew': 'TravisMathew (独立品牌)',
    'TravisMathew (北美)': 'TravisMathew (独立品牌)',
    'Johnnie-O': 'Johnnie-O (独立品牌)',
    'Greyson': 'Greyson (独立品牌)',
    'Linksoul': 'Linksoul (独立品牌)',
    'Malbon Golf': 'Malbon Golf (独立品牌)',
    'Eastside Golf': 'Eastside Golf (独立品牌)',
    'Bogey Boys': 'Bogey Boys (独立品牌)',
    'Radmor': 'Radmor (独立品牌)',
    'G/FORE': 'G/FORE (独立品牌, Peter Millar收购)',
    'Galvin Green': 'Galvin Green (独立品牌)',
    'Kjus': 'Kjus (独立品牌)',
    'J.Lindeberg': 'J.Lindeberg (独立品牌)',
    'Daily Sports': 'Daily Sports (独立品牌)',
    'Oscar Jacobson': 'Oscar Jacobson (独立品牌)',
    'Abacus': 'Abacus (独立品牌)',
    'Cross Sportswear': 'Cross Sportswear (独立品牌)',
    'Chervò': 'Chervò (独立品牌)',
    'Duca del Cosma': 'Duca del Cosma (独立品牌)',
    'Puma Golf': 'Puma SE',
    'Nike Golf': 'Nike, Inc.',
    'Adidas Golf': 'Adidas AG',
    'Under Armour Golf': 'Under Armour, Inc.',
    'Callaway': 'Topgolf Callaway Brands',
    'Titleist': 'Acushnet Company (Fila Holdings)',
    'FootJoy': 'Acushnet Company (Fila Holdings)',
    'TaylorMade': 'TaylorMade Golf (KPS Capital)',
    'Ping': 'PING (私营家族企业)',
    'PXG': 'Parsons Xtreme Golf (独立品牌)',
    'Cobra Golf': 'Puma SE',
    'Srixon': 'Sumitomo Rubber Industries',
    'Cleveland Golf': 'Sumitomo Rubber Industries',
    'XXIO': 'Sumitomo Rubber Industries',
    'Mizuno Golf': 'Mizuno Corporation',
    'Honma': 'Honma Golf (上市公司)',
    'Miura': 'Miura Golf (独立品牌)',
    'Epon': 'Epon Golf (Endo Manufacturing)',
    'Kyoei': 'Kyoei Golf (独立品牌)',
    'Fourteen': 'Fourteen Golf (独立品牌)',
    'Yamaha Golf': 'Yamaha Corporation',
    'PRGR': 'PRGR (Yokohama Rubber)',
    'OnCore': 'OnCore Golf (独立品牌)',
    'Vice Golf': 'Vice Golf (独立品牌)',
    'Sugar': 'Sugar Golf (独立品牌)',
    'Seed': 'Seed Golf (独立品牌)',
    'Cut': 'Cut Golf (独立品牌)',
    'Snell': 'Snell Golf (独立品牌)',
    'Kirkland': 'Costco (自有品牌)',
    'Inesis': 'Decathlon (自有品牌)',
    'Quince (cashmere)': 'Quince (独立品牌)',
    'Naadam (cashmere)': 'Naadam (独立品牌)',
    'White + Warren': 'White + Warren (独立品牌)',
    'Naked Cashmere': 'Naked Cashmere (独立品牌)',
    'Jenni Kayne': 'Jenni Kayne (独立品牌)',
    'Barefoot Dreams': 'Barefoot Dreams (独立品牌)',
    'Ugg': 'Deckers Brands',
    'UGG (Deckers)': 'Deckers Brands',
    'Emu Australia': 'Emu Australia (独立品牌)',
    'Mou': 'Mou (独立品牌)',
    'Koolaburra': 'Deckers Brands',
    'Bearpaw': 'Bearpaw (独立品牌)',
    'Minnetonka': 'Minnetonka (独立品牌)',
    'Softstar': 'Softstar Shoes (独立品牌)',
    'Manitobah': 'Manitobah Mukluks (原住民企业)',
    'Steger Mukluks': 'Steger Mukluks (独立品牌)',
    'L.L.Bean': 'L.L.Bean (私营家族企业)',
    'L.L.Bean (北美)': 'L.L.Bean (私营家族企业)',
    'Lands\' End': "Lands' End, Inc. (上市公司)",
    'Orvis': 'Orvis (私营家族企业)',
    'Filson': 'Filson (独立品牌)',
    'Barbour': 'Barbour (私营家族企业)',
    'Belstaff': 'Belstaff (独立品牌)',
    'Schott NYC': 'Schott NYC (私营家族企业)',
    'Vanson': 'Vanson Leathers (独立品牌)',
    'Langlitz': 'Langlitz Leathers (独立品牌)',
    'Aero Leather': 'Aero Leather Clothing (独立品牌)',
    'Simmons Bilt': 'Simmons Bilt (独立品牌)',
    'Himel Bros': 'Himel Bros (独立品牌)',
    'The Flat Head': 'The Flat Head (独立品牌)',
    'Iron Heart': 'Iron Heart (独立品牌)',
    'Samurai Jeans': 'Samurai Jeans (独立品牌)',
    'Momotaro': 'Momotaro Jeans (Japan Blue Group)',
    'Japan Blue': 'Japan Blue Group',
    'Pure Blue Japan': 'Pure Blue Japan (独立品牌)',
    'The Strike Gold': 'The Strike Gold (独立品牌)',
    'Oni Denim': 'Oni Denim (独立品牌)',
    'Tanuki': 'Tanuki (独立品牌)',
    'Studio D\'Artisan': "Studio D'Artisan (独立品牌)",
    'Fullcount': 'Fullcount (独立品牌)',
    'Warehouse': 'Warehouse & Co. (独立品牌)',
    'TCB': "TCB Jeans (独立品牌)",
    'Benzak': 'Benzak Denim Developers (独立品牌)',
    'Pike Brothers': 'Pike Brothers (独立品牌)',
    'Merz b. Schwanen': 'Merz b. Schwanen (独立品牌)',
    'Stevenson Overall': 'Stevenson Overall Co. (独立品牌)',
    'Mister Freedom': 'Mister Freedom (独立品牌)',
    'Rising Sun': 'Rising Sun & Co. (独立品牌)',
    'Rogue Territory': 'Rogue Territory (独立品牌)',
    '3sixteen': '3sixteen (独立品牌)',
    'Left Field NYC': 'Left Field NYC (独立品牌)',
    'Tellason': 'Tellason (独立品牌)',
    'Raleigh Denim': 'Raleigh Denim Workshop (独立品牌)',
    'Imogene + Willie': 'Imogene + Willie (独立品牌)',
    'Shockoe Atelier': 'Shockoe Atelier (独立品牌)',
    'Freenote Cloth': 'Freenote Cloth (独立品牌)',
    'Railcar Fine Goods': 'Railcar Fine Goods (独立品牌)',
    'Brave Star': 'Brave Star Selvage (独立品牌)',
    'Gustin': 'Gustin (独立品牌)',
    'Unbranded Brand': 'Unbranded Brand (Naked & Famous旗下)',
    'Naked & Famous': 'Naked & Famous Denim (独立品牌)',
    'Uniqlo (北美)': 'Fast Retailing',
    'Muji': 'Ryohin Keikaku (上市公司)',
    'Muji (北美)': 'Ryohin Keikaku (上市公司)',
    'Gu (Uniqlo sister)': 'Fast Retailing',
    'PLST': 'Fast Retailing',
    'Theory (Uniqlo)': 'Fast Retailing',
    'Comptoir des Cotonniers (Uniqlo)': 'Fast Retailing',
    'Princesse tam.tam (Uniqlo)': 'Fast Retailing',
    'J Brand (Uniqlo)': 'Fast Retailing',
    'Helmut Lang (Uniqlo)': 'Fast Retailing',
}


def apply_fixes():
    conn = sqlite3.connect(str(DB_PATH))
    cur = conn.cursor()
    changes = {'desc': 0, 'parent': 0}

    # ── 1. 英文描述→中文 ──
    print("=== 翻译英文描述 ===")
    for name, desc in DESC_TRANSLATIONS.items():
        cur.execute(
            "UPDATE brands SET description=?, updated_at=datetime('now') WHERE name=?",
            (desc, name)
        )
        if cur.rowcount > 0:
            changes['desc'] += 1
            print(f"  ✓ {name}")
        else:
            # Try with (北美) suffix
            cur.execute(
                "UPDATE brands SET description=?, updated_at=datetime('now') WHERE name=?",
                (desc, name + ' (北美)')
            )
            if cur.rowcount > 0:
                changes['desc'] += 1
                print(f"  ✓ {name} (北美)")

    conn.commit()
    print(f"  翻译完成: {changes['desc']} 个品牌\n")

    # ── 2. 补充母公司 ──
    print("=== 补充母公司 ===")
    for name, parent in PARENT_UPDATES.items():
        cur.execute(
            "UPDATE brands SET parent_company=?, updated_at=datetime('now') WHERE name=? AND (parent_company IS NULL OR parent_company='')",
            (parent, name)
        )
        if cur.rowcount > 0:
            changes['parent'] += 1

    conn.commit()
    print(f"  母公司补充: {changes['parent']} 个品牌\n")

    # ── 统计 ──
    total = cur.execute("SELECT COUNT(*) FROM brands").fetchone()[0]
    null_pc = cur.execute("SELECT COUNT(*) FROM brands WHERE parent_company IS NULL OR parent_company=''").fetchone()[0]
    
    import re
    rows = cur.execute("SELECT name, description FROM brands WHERE description IS NOT NULL AND description != ''").fetchall()
    pure_eng = sum(1 for r in rows if not re.search(r'[\u4e00-\u9fff]', r[1] or ''))
    
    print(f"=== 修复后统计 ===")
    print(f"母公司缺失: {null_pc}/{total}")
    print(f"纯英文描述: {pure_eng}/{total}")
    print(f"总修改: {sum(changes.values())}")

    conn.close()


if __name__ == '__main__':
    apply_fixes()
