#!/usr/bin/env python3
"""补充剩余品牌的母公司信息"""
import sqlite3
from pathlib import Path

DB_PATH = Path(__file__).parent.parent / "data" / "competitive_research.db"

PARENT_MAP = {
    # 知名品牌
    'Zegna': 'Ermenegildo Zegna Group (上市公司)',
    'Brunello Cucinelli': 'Brunello Cucinelli S.p.A. (上市公司)',
    'Max Mara': 'Max Mara Fashion Group (私营家族企业)',
    'Longchamp': 'Longchamp (私营家族企业)',
    'Goyard': 'Goyard (私营家族企业)',
    'Ralph Lauren': 'Ralph Lauren Corporation (上市公司)',
    'Spanx': 'Spanx (Blackstone投资)',
    'Good American': 'Good American (独立品牌)',
    'Warby Parker': 'Warby Parker Inc. (上市公司)',
    'New Era': 'New Era Cap (私营家族企业)',
    'Mackage': 'Mackage (独立品牌)',
    'Moose Knuckles': 'Moose Knuckles (独立品牌)',
    'Roa Hiking': 'Roa Hiking (独立品牌)',
    'John Elliott': 'John Elliott (独立品牌)',
    'Aime Leon Dore': 'Aimé Leon Dore (LVMH投资)',
    'Noah': 'Noah (独立品牌)',
    'Les Tien': 'Les Tien (独立品牌)',
    'Mansur Gavriel': 'Mansur Gavriel (独立品牌)',
    'Sarah Flint': 'Sarah Flint (独立品牌)',
    'Polène': 'Polène (独立品牌)',
    'Catbird': 'Catbird (独立品牌)',
    'Mejuri': 'Mejuri (独立品牌)',
    'Ana Luisa': 'Ana Luisa (独立品牌)',
    'Gorjana': 'Gorjana (独立品牌)',
    'BaubleBar': 'BaubleBar (独立品牌)',
    'Eileen Fisher': 'Eileen Fisher (私营家族企业)',
    'Tommy John': 'Tommy John (独立品牌)',
    'MeUndies': 'MeUndies (独立品牌)',
    'Ministry of Supply': 'Ministry of Supply (独立品牌)',
    'M.M.LaFleur': 'M.M.LaFleur (独立品牌)',
    'Universal Standard': 'Universal Standard (独立品牌)',
    'Torrid': 'Torrid Holdings Inc. (上市公司)',
    'Chicos': "Chico's FAS, Inc. (Sycamore Partners收购)",
    'Reformation': 'Reformation (Permira投资)',
    'Amour Vert': 'Amour Vert (独立品牌)',
    'Tradlands': 'Tradlands (独立品牌)',
    'Aday': 'Aday (独立品牌)',
    'Everlane': 'Everlane (Shein收购)',
    'Re/Done': 'Re/Done (独立品牌)',
    'Mother Denim': 'MOTHER Denim (独立品牌)',
    'Levi\'s': 'Levi Strauss & Co. (上市公司)',
    'Duer': 'DUER (独立品牌)',
    'Kit and Ace': 'Kit and Ace (独立品牌)',
    'Tentree': 'tentree (独立品牌)',
    'Nisolo': 'Nisolo (独立品牌)',
    'Thursday Boots': 'Thursday Boots (独立品牌)',
    'Taft': 'Taft (独立品牌)',
    'OluKai': 'OluKai (独立品牌)',
    'Dansko': 'Dansko (独立品牌)',
    'Kuru Footwear': 'KURU Footwear (独立品牌)',
    'Topo Athletic': 'Topo Athletic (独立品牌)',
    'Oiselle': 'Oiselle (独立品牌)',
    'Salming': 'Salming (独立品牌)',
    'Craft Sportswear': 'Craft Sportswear (独立品牌)',
    'Odlo': 'Odlo (Monte Rosa投资)',
    'X-Bionic': 'X-Bionic (独立品牌)',
    'Compressport': 'Compressport (独立品牌)',
    'Darn Tough': 'Darn Tough Vermont (Cabot Hosiery Mills)',
    'Feetures': 'Feetures (独立品牌)',
    'Injinji': 'Injinji (独立品牌)',
    'Balega': 'Balega (Implus Corporation)',
    'Outdoor Research': 'Outdoor Research (Danby Products)',
    'Royal Robbins': 'Royal Robbins (独立品牌)',
    'Kavu': 'KAVU (独立品牌)',
    'Duluth Pack': 'Duluth Pack (私营家族企业)',
    'Duluth Trading Co.': 'Duluth Holdings Inc. (上市公司)',
    'Danner': 'Danner (ABG/独立品牌)',
    'Mountain Equipment': 'Mountain Equipment (独立品牌)',
    'Sherpa Adventure Gear': 'Sherpa Adventure Gear (独立品牌)',
    'REI Co-op': 'REI Co-op (消费者合作社)',
    'Head': 'Head N.V. (上市公司)',
    'Babolat': 'Babolat (私营家族企业)',
    'Aether Apparel': 'Aether Apparel (独立品牌)',
    'Western Rise': 'Western Rise (独立品牌)',
    'Jjjjound': 'JJJJound (独立品牌)',
    'Cecilie Bahnsen': 'Cecilie Bahnsen (独立品牌)',
    'Stine Goya': 'Stine Goya (独立品牌)',
    'Rotate': 'Rotate (独立品牌)',
    'Self-Portrait': 'Self-Portrait (独立品牌)',
    'Vetements': 'Vetements (独立品牌)',
    'Marine Serre': 'Marine Serre (独立品牌)',
    'Coperni': 'Coperni (独立品牌)',
    'Pas Normal Studios': 'Pas Normal Studios (独立品牌)',
    'Mott & Bow': 'Mott & Bow (独立品牌)',
    'MATE the Label': 'MATE the Label (独立品牌)',
    'Boll & Branch': 'Boll & Branch (独立品牌)',
    'Brooklinen': 'Brooklinen (独立品牌)',
    'Parachute': 'Parachute (独立品牌)',
    'Béis': 'Béis (独立品牌)',
    'Calpak': 'Calpak (独立品牌)',
    'Away (Travel)': 'Away (独立品牌)',
    'Baboon to the Moon': 'Baboon to the Moon (独立品牌)',
    'Lo & Sons': 'Lo & Sons (独立品牌)',
    'State Bags': 'State Bags (独立品牌)',
    'Margaux': 'Margaux (独立品牌)',
    'Birdies': 'Birdies (独立品牌)',
    'Sarah Flint (NYC)': 'Sarah Flint (独立品牌)',
    'Left On Friday': 'Left On Friday (独立品牌)',
    'Solid & Striped': 'Solid & Striped (独立品牌)',
    'Monday Swimwear': 'Monday Swimwear (独立品牌)',
    'Frankies Bikinis': 'Frankies Bikinis (独立品牌)',
    'Year of Ours': 'Year of Ours (独立品牌)',
    'Joah Brown': 'Joah Brown (独立品牌)',
    'Carbon38': 'Carbon38 (独立品牌)',
    'Bombshell Sportswear': 'Bombshell Sportswear (独立品牌)',
    'NVGTN': 'NVGTN (独立品牌)',
    'CSB (Crop Shop Boutique)': 'CSB (独立品牌)',
    'Doyoueven': 'Doyoueven (独立品牌)',
    'Muscle Nation': 'Muscle Nation (独立品牌)',
    'Ryderwear': 'Ryderwear (独立品牌)',
    'AYBL': 'AYBL (独立品牌)',
    'TALA': 'TALA (独立品牌)',
    'LNDR': 'LNDR (独立品牌)',
    'P.E Nation': 'P.E Nation (独立品牌)',
    'Daily Drills': 'Daily Drills (独立品牌)',
    'Set Active': 'Set Active (独立品牌)',
    'Fleo': 'Fleo (独立品牌)',
    'Skins': 'Skins (独立品牌)',
    '2XU': '2XU (独立品牌)',
    'Koral': 'Koral (独立品牌)',
    'Alo': 'Alo Yoga (独立品牌)',
    'Beyond Yoga (Levi\'s)': 'Levi Strauss & Co.',
    'Vuori (独立)': 'Vuori (独立品牌)',
    'Outdoor Voices (独立)': 'Outdoor Voices (独立品牌)',
    'Girlfriend Collective (独立)': 'Girlfriend Collective (独立品牌)',
    'Parade': 'Parade (独立品牌)',
    'ThirdLove': 'ThirdLove (独立品牌)',
    'Negative Underwear': 'Negative Underwear (独立品牌)',
    'Eberjey': 'Eberjey (独立品牌)',
    'Knix': 'Knix (Essity收购)',
    'Cuup': 'CUUP (独立品牌)',
    'Lively': 'Lively (Wacoal收购)',
    'Jaanuu': 'Jaanuu (独立品牌)',
    'Little Sleepies': 'Little Sleepies (独立品牌)',
    'Kyte Baby': 'Kyte Baby (独立品牌)',
    'Monica + Andy': 'Monica + Andy (独立品牌)',
    'Rylee + Cru': 'Rylee + Cru (独立品牌)',
    'Tea Collection': 'Tea Collection (独立品牌)',
    'Angel Dear': 'Angel Dear (独立品牌)',
    'Hanna Andersson': 'Hanna Andersson (独立品牌)',
    'Primary': 'Primary (独立品牌)',
    'Kickee Pants': 'Kickee Pants (独立品牌)',
    'Burt\'s Bees Baby': "Burt's Bees Baby (独立品牌)",
    'Quay': 'Quay (独立品牌)',
    'Diff Eyewear': 'Diff Eyewear (独立品牌)',
    'Crap Eyewear': 'Crap Eyewear (独立品牌)',
    'Warby Parker (DTC)': 'Warby Parker Inc.',
    'David Yurman (NYC)': 'David Yurman (私营家族企业)',
    'Miansai (Miami)': 'Miansai (独立品牌)',
    'Alex and Ani (RI)': 'Alex and Ani (独立品牌)',
    'Gorjana (LA)': 'Gorjana (独立品牌)',
    'Mejuri (Toronto)': 'Mejuri (独立品牌)',
    'Catbird (NYC)': 'Catbird (独立品牌)',
    'Ana Luisa (NYC)': 'Ana Luisa (独立品牌)',
    'BaubleBar (NYC)': 'BaubleBar (独立品牌)',
    'Krost': 'KROST (独立品牌)',
    'Wolven': 'Wolven (独立品牌)',
    'Pangaia (UK)': 'Pangaia (独立品牌)',
    'Collina Strada (NYC)': 'Collina Strada (独立品牌)',
    'Stella McCartney (UK)': 'Stella McCartney (LVMH少数股权)',
    'Gabriela Hearst (NYC)': 'Gabriela Hearst (独立品牌)',
    'The Row (NYC)': 'The Row (Olsen姐妹独立品牌)',
    'Khaite (NYC)': 'Khaite (独立品牌)',
    'Toteme (Stockholm)': 'Toteme (独立品牌)',
    'Acne Studios (Stockholm)': 'Acne Studios (独立品牌)',
    'Isabel Marant (Paris)': 'Isabel Marant (独立品牌)',
    'Jacquemus (Paris)': 'Jacquemus (独立品牌)',
    'Ami (Paris)': 'AMI Paris (独立品牌)',
    'A.P.C. (Paris)': 'A.P.C. (独立品牌)',
    'Lemaire (Paris)': 'Lemaire (独立品牌)',
    'Courreges (Paris)': 'Courrèges (独立品牌)',
    'Mugler (Paris)': "L'Oréal (香水授权)",
    'Lanvin (Paris)': 'Lanvin Group (复星国际)',
    'Paco Rabanne (Paris)': 'Puig',
    'Jean Paul Gaultier (Paris)': 'Puig',
    'Nina Ricci (Paris)': 'Puig',
    'Dries Van Noten (Antwerp)': 'Puig',
    'Ann Demeulemeester (Antwerp)': 'Ann Demeulemeester (独立品牌)',
    'Haider Ackermann (Paris)': 'Haider Ackermann (独立品牌)',
    'JW Anderson (London)': 'LVMH (少数股权)',
    'Simone Rocha (London)': 'Simone Rocha (独立品牌)',
    'Erdem (London)': 'Erdem (独立品牌)',
    'Molly Goddard (London)': 'Molly Goddard (独立品牌)',
    'Roksanda (London)': 'Roksanda (独立品牌)',
    'Christopher Kane (London)': 'Christopher Kane (独立品牌)',
    'Victoria Beckham (London)': 'Victoria Beckham (独立品牌)',
    'Proenza Schouler (NYC)': 'Proenza Schouler (独立品牌)',
    'Altuzarra (NYC)': 'Altuzarra (独立品牌)',
    'Sandy Liang (NYC)': 'Sandy Liang (独立品牌)',
    'Eckhaus Latta (NYC)': 'Eckhaus Latta (独立品牌)',
    'Bode (NYC)': 'Bode (独立品牌)',
    'Peter Do (NYC)': 'Peter Do (独立品牌)',
    'Willy Chavarria (NYC)': 'Willy Chavarria (独立品牌)',
    'Luar (NYC)': 'Luar (独立品牌)',
    'Telfar (NYC)': 'Telfar (独立品牌)',
    'Dion Lee': 'Dion Lee (独立品牌)',
    'Christopher Esber': 'Christopher Esber (独立品牌)',
    'Zimmermann (Sydney)': 'Zimmermann (Advent International)',
    'Nanushka': 'Nanushka (独立品牌)',
    'Toteme': 'Toteme (独立品牌)',
    'Filippa K': 'Filippa K (独立品牌)',
    'Our Legacy': 'Our Legacy (独立品牌)',
    'Margaret Howell': 'Margaret Howell (独立品牌)',
    'Khaite': 'Khaite (独立品牌)',
    'Staud': 'Staud (独立品牌)',
    'Sézane': 'Sézane (独立品牌)',
    'Ganni': 'Ganni (独立品牌)',
    'Rouje': 'Rouje (独立品牌)',
    'Brock Collection': 'Brock Collection (独立品牌)',
    'Sea': 'Sea (独立品牌)',
    'Ulla Johnson': 'Ulla Johnson (独立品牌)',
    'LoveShackFancy': 'LoveShackFancy (独立品牌)',
    'A.L.C.': 'A.L.C. (独立品牌)',
    'Alice + Olivia (NYC)': 'Alice + Olivia (独立品牌)',
    'Veronica Beard': 'Veronica Beard (独立品牌)',
    'Frame (LA)': 'Frame (独立品牌)',
    'Mother (LA)': 'MOTHER Denim (独立品牌)',
    'Citizens of Humanity (LA)': 'Citizens of Humanity (独立品牌)',
    'Rag & Bone (NYC)': 'Rag & Bone (独立品牌)',
    '7 For All Mankind (LA)': 'Delta Galil Industries',
    'DL1961 (NYC)': 'DL1961 (独立品牌)',
    'Boyish (LA)': 'Boyish Jeans (独立品牌)',
    'Re/Done (LA)': 'Re/Done (独立品牌)',
    'Ética (LA)': 'Ética Denim (独立品牌)',
    'Outland Denim (AU)': 'Outland Denim (独立品牌)',
    'Ksubi (AU)': 'Ksubi (独立品牌)',
    'Rollas (AU)': 'Rollas Jeans (独立品牌)',
    'Neuw (AU)': 'Neuw Denim (独立品牌)',
    'Abrand (AU)': 'Abrand Jeans (独立品牌)',
    'Mavi (Turkey)': 'Mavi (上市公司)',
    'Silver Jeans Co. (Canada)': 'Silver Jeans Co. (独立品牌)',
    'Joe\'s Jeans (LA)': "Joe's Jeans (独立品牌)",
    'Hudson Jeans (LA)': 'Hudson Jeans (独立品牌)',
    'Lucky Brand (LA)': 'Authentic Brands Group / SPARC Group',
    'Greats (NYC)': 'Steve Madden',
    'Oliver Cabell (LA)': 'Oliver Cabell (独立品牌)',
    'Beckett Simonon (Miami)': 'Beckett Simonon (独立品牌)',
    'Koio (NYC)': 'Koio (独立品牌)',
    'Axel Arigato (Sweden)': 'Axel Arigato (独立品牌)',
    'Veja (Paris)': 'VEJA (独立品牌)',
    'Cariuma (Brazil)': 'Cariuma (独立品牌)',
    'Allbirds (SF)': 'Allbirds, Inc. (上市公司)',
    'Rothy\'s (SF)': "Rothy's (独立品牌)",
    'Vessi (Canada)': 'Vessi (独立品牌)',
    'Native Shoes (Canada)': 'Native Shoes (独立品牌)',
    'Oofos (Boston)': 'Oofos (独立品牌)',
    'Hoka (Deckers)': 'Deckers Brands',
    'On (Swiss)': 'On Holding AG (上市公司)',
    'Salomon (France)': 'Amer Sports (安踏体育)',
    'Satisfy Running (France)': 'Satisfy Running (独立品牌)',
    'Tracksmith (Boston)': 'Tracksmith (独立品牌)',
    'Bandit Running (NYC)': 'Bandit Running (独立品牌)',
    'District Vision (NYC)': 'District Vision (独立品牌)',
    'Janji (Boston)': 'Janji (独立品牌)',
    'Ciele Athletics (Canada)': 'Ciele Athletics (独立品牌)',
    'Rabbitt (SF)': 'Rabbitt (独立品牌)',
    'Wolaco (NYC)': 'Wolaco (独立品牌)',
    'Path Projects (SF)': 'Path Projects (独立品牌)',
    'Nobull (Boston)': 'Nobull (独立品牌)',
    'R.A.D. (UK)': 'R.A.D. (独立品牌)',
    'Nnormal (Spain)': 'Nnormal (独立品牌)',
    'Speedland (Portland)': 'Speedland (独立品牌)',
    'Mystery Ranch (MT)': 'Yeti Holdings',
    'Osprey (CO)': 'Helen of Troy Limited',
    'Gregory (CA)': 'Samsonite',
    'Deuter (Germany)': 'Deuter Sport GmbH',
    'Thule (Sweden)': 'Thule Group AB',
    'Yakima (OR)': 'Yakima Products, Inc.',
    'Hydro Flask (OR)': 'Helen of Troy Limited',
    'Stanley (WA)': 'Stanley (PMI Worldwide)',
    'Owala (UT)': 'Owala (独立品牌)',
    'Corkcicle (FL)': 'Corkcicle (独立品牌)',
    'Brumate (CO)': 'Brumate (独立品牌)',
    'Simple Modern (OK)': 'Simple Modern (独立品牌)',
    'RTIC (TX)': 'RTIC Outdoors',
    'Orca (TN)': 'Orca (独立品牌)',
    'Pelican (CA)': 'Pelican Products, Inc.',
    'YETI (TX)': 'YETI Holdings, Inc.',
    'Engel (MI)': 'Engel Coolers (独立品牌)',
    'Grizzly (IA)': 'Grizzly Coolers (独立品牌)',
    'Kong (MN)': 'Kong Coolers (独立品牌)',
    'Bison (TX)': 'Bison Coolers (独立品牌)',
    'Hydro Flask (Helen of Troy)': 'Helen of Troy Limited',
    'Osprey (Helen of Troy)': 'Helen of Troy Limited',
    'Fjällräven (Sweden)': 'Fenix Outdoor International AG',
    'Haglöfs (Sweden)': 'ASICS Corporation',
    'Norrona (Norway)': 'Norrona Sport AS',
    'Mammut (Swiss)': 'Telemos Capital',
    'Black Diamond (UT)': 'Clarus Corporation',
    'Petzl (France)': 'Petzl (私营家族企业)',
    'La Sportiva (Italy)': 'La Sportiva (私营家族企业)',
    'Scarpa (Italy)': 'Scarpa (私营家族企业)',
    'Mountain Hardwear (Columbia)': 'Columbia Sportswear',
    'prAna (Columbia)': 'Columbia Sportswear',
    'Sorel (Columbia)': 'Columbia Sportswear',
    'Helly Hansen (Norway)': 'Canadian Tire Corporation',
    'Musto (UK)': 'Helly Hansen (Canadian Tire)',
    'Grundéns (Sweden)': 'Grundéns (独立品牌)',
    'Xtratuf (AK)': 'Xtratuf (独立品牌)',
    'Muck Boot (TX)': 'Muck Boot (独立品牌)',
    'Bogs (OR)': 'Bogs (独立品牌)',
    'Kamik (Canada)': 'Kamik (独立品牌)',
    'Pajar (Canada)': 'Pajar (独立品牌)',
    'La Canadienne (Canada)': 'La Canadienne (独立品牌)',
    'Aquatalia (Italy)': 'Aquatalia (独立品牌)',
    'Blondo (Canada)': 'Blondo (独立品牌)',
    'Blundstone (AU)': 'Blundstone (私营家族企业)',
    'Dr. Martens (UK)': 'Dr. Martens plc (上市公司)',
    'Clarks (UK)': 'Clarks (私营家族企业)',
    'Birkenstock (Germany)': 'Birkenstock Holding plc (上市公司)',
    'Birkenstock 1774 (Germany)': 'Birkenstock Holding plc',
    'Crocs (CO)': 'Crocs, Inc.',
    'Heydude (Crocs)': 'Crocs, Inc.',
    'Skechers (CA)': 'Skechers USA, Inc.',
    'Steve Madden (NY)': 'Steve Madden, Ltd.',
    'Aldo (Canada)': 'Aldo Group',
    'Call It Spring (Canada)': 'Aldo Group',
    'Globo (Canada)': 'Aldo Group',
    'DSW (OH)': 'Designer Brands Inc.',
    'Famous Footwear (MO)': 'Caleres, Inc.',
    'Sam Edelman (NY)': 'Caleres, Inc.',
    'Naturalizer (MO)': 'Caleres, Inc.',
    'Vionic (CA)': 'Caleres, Inc.',
    'Franco Sarto (CA)': 'Caleres, Inc.',
    'Dr. Scholl\'s Shoes (MO)': 'Caleres, Inc.',
    'Rykä (MO)': 'Caleres, Inc.',
    'LifeStride (MO)': 'Caleres, Inc.',
    'Bzees (MO)': 'Caleres, Inc.',
    'Blowfish Malibu (CA)': 'Caleres, Inc.',
    'Circus by Sam Edelman (NY)': 'Caleres, Inc.',
    'Vince (LA)': 'Vince Holding Corp.',
    'Theory (NY)': 'Fast Retailing (优衣库母公司)',
    'Helmut Lang (NY)': 'Fast Retailing (优衣库母公司)',
    'Comptoir des Cotonniers (Paris)': 'Fast Retailing',
    'Princesse tam.tam (Paris)': 'Fast Retailing',
    'J Brand (LA)': 'Fast Retailing',
    'AG Jeans (LA)': 'AG Adriano Goldschmied (独立品牌)',
    'Paige (LA)': 'PAIGE (独立品牌)',
    'Mother (LA denim)': 'MOTHER Denim (独立品牌)',
    'Nudie Jeans (Sweden)': 'Nudie Jeans (独立品牌)',
    'G-Star RAW (NL)': 'G-Star RAW (独立品牌)',
    'Mavi (Istanbul)': 'Mavi (上市公司)',
    'Naked & Famous (Canada)': 'Naked & Famous Denim (独立品牌)',
    'Unbranded Brand (Canada)': 'Naked & Famous Denim',
    'Gustin (SF)': 'Gustin (独立品牌)',
    'Brave Star (LA)': 'Brave Star Selvage (独立品牌)',
    'Railcar Fine Goods (LA)': 'Railcar Fine Goods (独立品牌)',
    'Freenote Cloth (CA)': 'Freenote Cloth (独立品牌)',
    'Shockoe Atelier (VA)': 'Shockoe Atelier (独立品牌)',
    'Imogene + Willie (TN)': 'Imogene + Willie (独立品牌)',
    'Raleigh Denim (NC)': 'Raleigh Denim Workshop (独立品牌)',
    'Tellason (SF)': 'Tellason (独立品牌)',
    'Left Field NYC (NY)': 'Left Field NYC (独立品牌)',
    '3sixteen (NY)': '3sixteen (独立品牌)',
    'Rogue Territory (LA)': 'Rogue Territory (独立品牌)',
    'Rising Sun (CA)': 'Rising Sun & Co. (独立品牌)',
    'Mister Freedom (LA)': 'Mister Freedom (独立品牌)',
    'Stevenson Overall (CA)': 'Stevenson Overall Co. (独立品牌)',
    'Merz b. Schwanen (Germany)': 'Merz b. Schwanen (独立品牌)',
    'Iron Heart (Japan)': 'Iron Heart (独立品牌)',
    'Samurai Jeans (Japan)': 'Samurai Jeans (独立品牌)',
    'Momotaro (Japan)': 'Momotaro Jeans (Japan Blue Group)',
    'Japan Blue (Japan)': 'Japan Blue Group',
    'Pure Blue Japan (Japan)': 'Pure Blue Japan (独立品牌)',
    'Oni Denim (Japan)': 'Oni Denim (独立品牌)',
    'Tanuki (Japan)': 'Tanuki (独立品牌)',
    "Studio D'Artisan (Japan)": "Studio D'Artisan (独立品牌)",
    'Fullcount (Japan)': 'Fullcount (独立品牌)',
    'Warehouse (Japan)': 'Warehouse & Co. (独立品牌)',
    'TCB (Japan)': 'TCB Jeans (独立品牌)',
    'The Flat Head (Japan)': 'The Flat Head (独立品牌)',
    'Benzak (NL)': 'Benzak Denim Developers (独立品牌)',
    'Pike Brothers (Germany)': 'Pike Brothers (独立品牌)',
    'Schott NYC (NJ)': 'Schott NYC (私营家族企业)',
    'Barbour (UK)': 'Barbour (私营家族企业)',
    'Filson (WA)': 'Filson (独立品牌)',
    'Belstaff (UK)': 'Belstaff (独立品牌)',
    'L.L.Bean (ME)': 'L.L.Bean (私营家族企业)',
    "Lands' End (WI)": "Lands' End, Inc. (上市公司)",
    'Orvis (VT)': 'Orvis (私营家族企业)',
    'Fjällräven (Fenix Outdoor)': 'Fenix Outdoor International AG',
    'Haglöfs (ASICS)': 'ASICS Corporation',
    'Mammut (Telemos)': 'Telemos Capital',
    'Black Diamond (Clarus)': 'Clarus Corporation',
    'Cotopaxi (UT)': 'Cotopaxi (独立品牌)',
    'Nomatic (UT)': 'Nomatic (独立品牌)',
    'Timbuk2 (SF)': 'Timbuk2 (独立品牌)',
    'Peak Design (SF)': 'Peak Design (独立品牌)',
    'Bellroy (AU)': 'Bellroy (独立品牌)',
    'AER (SF)': 'AER (独立品牌)',
    'Evergoods (MT)': 'Evergoods (独立品牌)',
    'Topo Designs (CO)': 'Topo Designs (独立品牌)',
    'Roark (CA)': 'Roark (独立品牌)',
    'KÜHL (UT)': 'KÜHL (独立品牌)',
    'Marine Layer (SF)': 'Marine Layer (独立品牌)',
    'Buck Mason (LA)': 'Buck Mason (独立品牌)',
    'Taylor Stitch (SF)': 'Taylor Stitch (独立品牌)',
    'Flint and Tinder (Huckberry)': 'Huckberry',
    'Relwen (OH)': 'Relwen (独立品牌)',
    'Faherty (NY)': 'Faherty (独立品牌)',
    'Jungmaven (WA)': 'Jungmaven (独立品牌)',
    'Rhone (CT)': 'Rhone (独立品牌)',
    'Mizzen+Main (TX)': 'Mizzen+Main (独立品牌)',
    'State and Liberty (MI)': 'State and Liberty (独立品牌)',
    'Untuckit (NY)': 'UNTUCKit (独立品牌)',
    'Bonobos (NY)': 'Express, Inc. / WHP Global',
    'Peter Millar (NC)': 'Richemont',
    'TravisMathew (CA)': 'TravisMathew (独立品牌)',
    'Johnnie-O (CA)': 'Johnnie-O (独立品牌)',
    'Greyson (MI)': 'Greyson (独立品牌)',
    'Linksoul (CA)': 'Linksoul (独立品牌)',
    'Malbon Golf (LA)': 'Malbon Golf (独立品牌)',
    'Eastside Golf (GA)': 'Eastside Golf (独立品牌)',
    'Bogey Boys (WA)': 'Bogey Boys (独立品牌)',
    'Radmor (WA)': 'Radmor (独立品牌)',
    'G/FORE (LA)': 'G/FORE (Peter Millar/Richemont收购)',
    'Galvin Green (Sweden)': 'Galvin Green (独立品牌)',
    'Kjus (Switzerland)': 'Kjus (独立品牌)',
    'J.Lindeberg (Sweden)': 'J.Lindeberg (独立品牌)',
    'Peak Performance (Amer Sports)': 'Amer Sports (安踏体育)',
    'Arc\'teryx (Amer Sports)': 'Amer Sports (安踏体育)',
    'Atomic (Amer Sports)': 'Amer Sports (安踏体育)',
    'Wilson (Amer Sports)': 'Amer Sports (安踏体育)',
    'Salomon (Amer Sports)': 'Amer Sports (安踏体育)',
    'Suunto (Amer Sports)': 'Amer Sports (安踏体育)',
    'Precor (Amer Sports)': 'Amer Sports (安踏体育)',
    'Patagonia (private)': 'Patagonia, Inc. / Holdfast Collective',
    'New Balance (private)': 'New Balance (私营)',
    'Brooks (Berkshire)': 'Berkshire Hathaway (Brooks Running)',
    'ASICS (Japan)': 'ASICS Corporation',
    'Mizuno (Japan)': 'Mizuno Corporation',
    'Puma (Germany)': 'Puma SE',
    'Under Armour (MD)': 'Under Armour, Inc.',
    'Lululemon (Canada)': 'Lululemon Athletica, Inc.',
    'Athleta (Gap)': 'Gap Inc.',
    'Fabletics (LA)': 'TechStyle Fashion Group',
    'Gymshark (UK)': 'Gymshark (独立品牌)',
    'Sweaty Betty (UK)': 'Sweaty Betty (Wolverine Worldwide)',
    'Varley (UK)': 'Varley (独立品牌)',
    'Alo Yoga (LA)': 'Alo Yoga (独立品牌)',
    'Vuori (CA)': 'Vuori (独立品牌)',
    'Outdoor Voices (TX)': 'Outdoor Voices (独立品牌)',
    'Ten Thousand (NY)': 'Ten Thousand (独立品牌)',
    'Rhone (CT active)': 'Rhone (独立品牌)',
    'Mack Weldon (NY)': 'Mack Weldon (独立品牌)',
    'Public Rec (IL)': 'Public Rec (独立品牌)',
    'Birddogs (NY)': 'Birddogs (独立品牌)',
    'Myles Apparel (SF)': 'Myles Apparel (独立品牌)',
    'Bombas (NY)': 'Bombas (独立品牌)',
    'Naadam (NY)': 'Naadam (独立品牌)',
    'Quince (SF)': 'Quince (独立品牌)',
    'Cuyana (SF)': 'Cuyana (独立品牌)',
    'Dagne Dover (NY)': 'Dagne Dover (独立品牌)',
    'MZ Wallace (NY)': 'MZ Wallace (独立品牌)',
    'Senreve (SF)': 'Senreve (独立品牌)',
    'Paravel (NY)': 'Paravel (独立品牌)',
    'M.Gemi (Boston)': 'M.Gemi (独立品牌)',
    'Margaux (NY)': 'Margaux (独立品牌)',
    'Away (NY)': 'Away (独立品牌)',
    'Italic (LA)': 'Italic (独立品牌)',
    'Everlane (SF)': 'Shein',
    'Reformation (LA)': 'Reformation (Permira投资)',
    'Sézane (Paris)': 'Sézane (独立品牌)',
    'Rouje (Paris)': 'Rouje (独立品牌)',
    'Ganni (Copenhagen)': 'Ganni (独立品牌)',
    'Staud (LA)': 'Staud (独立品牌)',
    'Khaite (NY)': 'Khaite (独立品牌)',
    'Toteme (Stockholm brand)': 'Toteme (独立品牌)',
    'Acne Studios (Stockholm brand)': 'Acne Studios (独立品牌)',
    'Isabel Marant (Paris brand)': 'Isabel Marant (独立品牌)',
    'Jacquemus (Paris brand)': 'Jacquemus (独立品牌)',
    'Ami (Paris brand)': 'AMI Paris (独立品牌)',
    'A.P.C. (Paris brand)': 'A.P.C. (独立品牌)',
    'Lemaire (Paris brand)': 'Lemaire (独立品牌)',
    'Amiri (LA)': 'Amiri (独立品牌)',
    'Rhude (LA)': 'Rhude (独立品牌)',
    'Fear of God (LA)': 'Fear of God (独立品牌)',
    'Kith (NY)': 'Kith (独立品牌)',
    'Stone Island (Italy)': 'Moncler Group',
    'Palm Angels (Italy)': 'Palm Angels (New Guards Group)',
    'Heron Preston (NY)': 'Heron Preston (独立品牌)',
    'A-Cold-Wall* (UK)': 'A-Cold-Wall* (独立品牌)',
    'Represent (UK)': 'Represent (独立品牌)',
    'Cole Buxton (UK)': 'Cole Buxton (独立品牌)',
    'Gallery Dept. (LA)': 'Gallery Dept. (独立品牌)',
    'Denim Tears (NY)': 'Denim Tears (独立品牌)',
    'Who Decides War (NY)': 'Who Decides War (独立品牌)',
    'Pyer Moss (NY)': 'Pyer Moss (独立品牌)',
    'Telfar (NY brand)': 'Telfar (独立品牌)',
    'Wales Bonner (UK)': 'Wales Bonner (独立品牌)',
    'Martine Rose (UK)': 'Martine Rose (独立品牌)',
    'Bianca Saunders (UK)': 'Bianca Saunders (独立品牌)',
    'Nicholas Daley (UK)': 'Nicholas Daley (独立品牌)',
    'Ahluwalia (UK)': 'Ahluwalia (独立品牌)',
    'Chopova Lowena (UK)': 'Chopova Lowena (独立品牌)',
    'Supriya Lele (UK)': 'Supriya Lele (独立品牌)',
    'Knwls (UK)': 'Knwls (独立品牌)',
    'Ottolinger (Berlin)': 'Ottolinger (独立品牌)',
    'Palomo Spain (Spain)': 'Palomo Spain (独立品牌)',
    'Marni (Italy)': 'OTB Group (Only The Brave)',
    'Diesel (Italy)': 'OTB Group (Only The Brave)',
    'Jil Sander (Germany)': 'OTB Group (Only The Brave)',
    'Maison Margiela (France)': 'OTB Group (Only The Brave)',
    'Viktor & Rolf (NL)': 'OTB Group (Only The Brave)',
    'Amiri (LA luxury)': 'Amiri (独立品牌)',
    'Rhude (LA luxury)': 'Rhude (独立品牌)',
    'Fear of God (LA luxury)': 'Fear of God (独立品牌)',
    'Gallery Dept. (LA luxury)': 'Gallery Dept. (独立品牌)',
    'Denim Tears (NY luxury)': 'Denim Tears (独立品牌)',
    'Miu Miu (Italy)': 'Prada Group',
    'Polo Ralph Lauren (NY)': 'Ralph Lauren Corporation',
    'Tommy Hilfiger (NY)': 'PVH Corp',
    'Calvin Klein (NY)': 'PVH Corp',
    'H&M (Sweden)': 'H&M Group',
    'COS (London)': 'H&M Group',
    '& Other Stories (Sweden)': 'H&M Group',
    'Arket (Sweden)': 'H&M Group',
    'Weekday (Sweden)': 'H&M Group',
    'Monki (Sweden)': 'H&M Group',
    'Massimo Dutti (Spain)': 'Inditex',
    'Bershka (Spain)': 'Inditex',
    'Pull&Bear (Spain)': 'Inditex',
    'Stradivarius (Spain)': 'Inditex',
    'Zara Home (Spain)': 'Inditex',
    'Zara (Spain)': 'Inditex',
    'Sandro (Paris)': 'SMCP Group',
    'Maje (Paris)': 'SMCP Group',
    'Claudie Pierlot (Paris)': 'SMCP Group',
    'Urban Outfitters (PA)': 'Urban Outfitters, Inc. (URBN)',
    'Anthropologie (PA)': 'Urban Outfitters, Inc. (URBN)',
    'Free People (PA)': 'Urban Outfitters, Inc. (URBN)',
    'Nuuly (PA)': 'Urban Outfitters, Inc. (URBN)',
    'FP Movement (PA)': 'Urban Outfitters, Inc. (URBN)',
    'BHLDN (PA)': 'Urban Outfitters, Inc. (URBN)',
    'Terrain (PA)': 'Urban Outfitters, Inc. (URBN)',
    'Madewell (NY)': 'J.Crew Group',
    'J.Crew (NY)': 'J.Crew Group',
    'Banana Republic (SF)': 'Gap Inc.',
    'Gap (SF)': 'Gap Inc.',
    'Old Navy (SF)': 'Gap Inc.',
    'Athleta (SF)': 'Gap Inc.',
    'Hollister (OH)': 'Abercrombie & Fitch Co.',
    'Abercrombie & Fitch (OH)': 'Abercrombie & Fitch Co.',
    'American Eagle (PA)': 'American Eagle Outfitters, Inc.',
    'Aerie (PA)': 'American Eagle Outfitters, Inc.',
    'Off-White (Italy)': 'Off-White (LVMH收购)',
    'Coach (NY)': 'Tapestry, Inc.',
    'Kate Spade (NY)': 'Tapestry, Inc.',
    'Stuart Weitzman (NY)': 'Tapestry, Inc.',
    'Michael Kors (NY)': 'Capri Holdings',
    'Versace (Italy)': 'Capri Holdings',
    'Jimmy Choo (UK)': 'Capri Holdings',
    'Burberry (UK)': 'Burberry Group plc (上市公司)',
    'Prada (Italy)': 'Prada Group (上市公司)',
    'Hermès (France)': 'Hermès International (上市公司)',
    'Chanel (France)': 'Chanel (私营)',
    'Gucci (Italy)': 'Kering',
    'Saint Laurent (France)': 'Kering',
    'Bottega Veneta (Italy)': 'Kering',
    'Balenciaga (France)': 'Kering',
    'Alexander McQueen (UK)': 'Kering',
    'Louis Vuitton (France)': 'LVMH',
    'Dior (France)': 'LVMH',
    'Fendi (Italy)': 'LVMH',
    'Givenchy (France)': 'LVMH',
    'Celine (France)': 'LVMH',
    'Loewe (Spain)': 'LVMH',
    'Marc Jacobs (NY)': 'LVMH',
    'Rimowa (Germany)': 'LVMH',
    'Tiffany & Co. (NY)': 'LVMH',
    'Bulgari (Italy)': 'LVMH',
    'Loro Piana (Italy)': 'LVMH',
    'Kenzo (France)': 'LVMH',
    'Berluti (France)': 'LVMH',
    'Emilio Pucci (Italy)': 'LVMH',
    'Hublot (Swiss)': 'LVMH',
    'TAG Heuer (Swiss)': 'LVMH',
    'Cartier (France)': 'Richemont',
    'Van Cleef & Arpels (France)': 'Richemont',
    'Chloé (France)': 'Richemont',
    'Montblanc (Germany)': 'Richemont',
    'Piaget (Swiss)': 'Richemont',
    'Jaeger-LeCoultre (Swiss)': 'Richemont',
    'IWC Schaffhausen (Swiss)': 'Richemont',
    'Vacheron Constantin (Swiss)': 'Richemont',
    'Panerai (Italy)': 'Richemont',
    'Peter Millar (Richemont)': 'Richemont',
    'Zegna (Italy)': 'Ermenegildo Zegna Group',
    'Moncler (Italy)': 'Moncler Group',
    'Brunello Cucinelli (Italy)': 'Brunello Cucinelli S.p.A.',
    'Max Mara (Italy)': 'Max Mara Fashion Group',
    'Longchamp (France)': 'Longchamp (私营家族企业)',
    'Goyard (France)': 'Goyard (私营家族企业)',
    'Ralph Lauren (NY)': 'Ralph Lauren Corporation',
    'Polo Ralph Lauren (NY brand)': 'Ralph Lauren Corporation',
    'Nike (OR)': 'Nike, Inc.',
    'Adidas (Germany)': 'Adidas AG',
    'Converse (MA)': 'Nike, Inc.',
    'Jordan (OR)': 'Nike, Inc.',
    'Vans (CA)': 'VF Corporation',
    'The North Face (CO)': 'VF Corporation',
    'Timberland (NH)': 'VF Corporation',
    'Dickies (TX)': 'VF Corporation',
    'JanSport (WA)': 'VF Corporation',
    'Smartwool (CO)': 'VF Corporation',
    'Icebreaker (NZ)': 'VF Corporation',
    'Altra (UT)': 'VF Corporation',
    'Eastpak (MA)': 'VF Corporation',
    'Kipling (Belgium)': 'VF Corporation',
    'Napapijri (Italy)': 'VF Corporation',
    'Carhartt (MI)': 'Carhartt, Inc. (私营家族企业)',
    'Carhartt WIP (Germany)': 'Carhartt, Inc. (授权Work In Progress)',
    "Levi's (SF)": 'Levi Strauss & Co.',
    'Dockers (SF)': 'Levi Strauss & Co.',
    'Beyond Yoga (SF)': 'Levi Strauss & Co.',
    'Wrangler (NC)': 'Kontoor Brands',
    'Lee (KS)': 'Kontoor Brands',
    'Rock & Republic (CA)': 'VF Corporation',
    'Columbia Sportswear (OR)': 'Columbia Sportswear Company',
    'Sorel (OR)': 'Columbia Sportswear Company',
    'Mountain Hardwear (OR)': 'Columbia Sportswear Company',
    'prAna (CA)': 'Columbia Sportswear Company',
    'Patagonia (CA)': 'Patagonia, Inc. / Holdfast Collective',
    'REI Co-op (WA)': 'REI Co-op (消费者合作社)',
    'Canada Goose (Canada)': 'Canada Goose Holdings Inc. (上市公司)',
    'Moose Knuckles (Canada)': 'Moose Knuckles (独立品牌)',
    'Mackage (Canada)': 'Mackage (独立品牌)',
    'Nobis (Canada)': 'Nobis (独立品牌)',
    'Parajumpers (Italy)': 'Parajumpers (独立品牌)',
    'Woolrich (PA)': 'Woolrich (独立品牌)',
    'Pendleton (OR)': 'Pendleton Woolen Mills (私营家族企业)',
    'Keen (OR)': 'KEEN (独立品牌)',
    'Merrell (MI)': 'Wolverine Worldwide',
    'Saucony (MA)': 'Wolverine Worldwide',
    'Sperry (MA)': 'Wolverine Worldwide',
    'Keds (MA)': 'Wolverine Worldwide',
    'Hush Puppies (MI)': 'Wolverine Worldwide',
    'Wolverine (MI)': 'Wolverine Worldwide',
    'Cat Footwear (MI)': 'Wolverine Worldwide (Caterpillar授权)',
    'Chaco (MI)': 'Wolverine Worldwide',
    'New Balance (MA)': 'New Balance (私营)',
    'Brooks (WA)': 'Berkshire Hathaway (Brooks Running)',
    'ASICS (Japan HQ)': 'ASICS Corporation',
    'On (Switzerland)': 'On Holding AG (上市公司)',
    'Hoka (CA)': 'Deckers Brands',
    'UGG (CA)': 'Deckers Brands',
    'Teva (CA)': 'Deckers Brands',
    'Sanuk (CA)': 'Deckers Brands',
    'Crocs (CO)': 'Crocs, Inc.',
    'Heydude (Italy)': 'Crocs, Inc.',
    'Skechers (CA HQ)': 'Skechers USA, Inc.',
    'Puma (Germany HQ)': 'Puma SE',
    'Under Armour (MD HQ)': 'Under Armour, Inc.',
    'Lululemon (Canada HQ)': 'Lululemon Athletica, Inc.',
    'Alo Yoga (LA HQ)': 'Alo Yoga (独立品牌)',
    'Vuori (CA HQ)': 'Vuori (独立品牌)',
    'Uniqlo (Japan)': 'Fast Retailing',
    'Muji (Japan)': 'Ryohin Keikaku',
    'Shein (China)': 'Shein Group',
    'Fashion Nova (CA)': 'Fashion Nova (独立品牌)',
    'SKIMS (CA)': 'SKIMS (独立品牌)',
    'Good American (CA)': 'Good American (独立品牌)',
    'Spanx (GA)': 'Spanx (Blackstone投资)',
    'Yeezy (CA)': 'Yeezy (独立品牌)',
    'Supreme (NY)': 'EssilorLuxottica (VF Corp出售)',
    'Stüssy (CA)': 'Stüssy (独立品牌)',
    'Palace (UK)': 'Palace Skateboards (独立品牌)',
    'Bape (Japan)': 'BAPE (I.T Group, 香港)',
    'A Bathing Ape (Japan)': 'I.T Group (香港)',
    'Human Made (Japan)': 'Human Made (独立品牌)',
    'Neighborhood (Japan)': 'Neighborhood (独立品牌)',
    'WTAPS (Japan)': 'WTAPS (独立品牌)',
    'Visvim (Japan)': 'Visvim (独立品牌)',
    'Kapital (Japan)': 'Kapital (独立品牌)',
    'Engineered Garments (NY)': 'Engineered Garments (独立品牌)',
    'Needles (Japan)': 'Needles (Nepenthes)',
    'South2 West8 (Japan)': 'Nepenthes',
    'White Mountaineering (Japan)': 'White Mountaineering (独立品牌)',
    'And Wander (Japan)': 'And Wander (独立品牌)',
    'Nanamica (Japan)': 'Nanamica (独立品牌)',
    'Snow Peak (Japan)': 'Snow Peak (上市公司)',
    'Goldwin (Japan)': 'Goldwin Inc. (上市公司)',
    'Descente (Japan)': 'Descente Ltd. (上市公司)',
    'Phenix (Japan)': 'Phenix (独立品牌)',
    'Burton (VT)': 'Burton Snowboards (私营)',
    'Volcom (CA)': 'Authentic Brands Group',
    'Quiksilver (CA)': 'Authentic Brands Group',
    'Billabong (AU)': 'Authentic Brands Group',
    'Roxy (CA)': 'Authentic Brands Group',
    'RVCA (CA)': 'Authentic Brands Group',
    'Element (CA)': 'Authentic Brands Group',
    'DC Shoes (CA)': 'Authentic Brands Group',
    'Etnies (CA)': 'Etnies (独立品牌)',
    'éS (CA)': 'Sole Technology',
    'Emerica (CA)': 'Sole Technology',
    'Lakai (CA)': 'Lakai (独立品牌)',
    'Nike SB (OR)': 'Nike, Inc.',
    'Adidas Skateboarding (Germany)': 'Adidas AG',
    'New Balance Numeric (MA)': 'New Balance',
    'Vans Skateboarding (CA)': 'VF Corporation',
    'Converse CONS (MA)': 'Nike, Inc.',
    'HUF (CA)': 'HUF (独立品牌)',
    'Primitive (CA)': 'Primitive Skateboarding (独立品牌)',
    'April Skateboards (CA)': 'April Skateboards (独立品牌)',
    'Polar Skate Co. (Sweden)': 'Polar Skate Co. (独立品牌)',
    'Palace (UK brand)': 'Palace Skateboards (独立品牌)',
    'Dime (Canada)': 'Dime (独立品牌)',
    'Alltimers (NY)': 'Alltimers (独立品牌)',
    'Fucking Awesome (CA)': 'Fucking Awesome (独立品牌)',
    'Bianca Chandon (NY)': 'Bianca Chandon (独立品牌)',
    'Noah (NY brand)': 'Noah (独立品牌)',
    'Awake NY (NY)': 'Awake NY (独立品牌)',
    'Brain Dead (CA)': 'Brain Dead (独立品牌)',
    'Online Ceramics (CA)': 'Online Ceramics (独立品牌)',
    'Pleasures (CA)': 'Pleasures (独立品牌)',
    'Chinatown Market (NY)': 'Chinatown Market (独立品牌)',
    'Ripndip (CA)': 'Ripndip (独立品牌)',
    'The Hundreds (CA)': 'The Hundreds (独立品牌)',
    'Diamond Supply Co. (CA)': 'Diamond Supply Co. (独立品牌)',
    'Obey (CA)': 'Obey Clothing (独立品牌)',
    'Brixton (CA)': 'Brixton (独立品牌)',
    'Melin (CA)': 'Melin (独立品牌)',
    'Lack of Color (AU)': 'Lack of Color (独立品牌)',
    'Janessa Leoné (CA)': 'Janessa Leoné (独立品牌)',
    'Gigi Burris (NY)': 'Gigi Burris Millinery (独立品牌)',
    'Clyde (NY)': 'Clyde (独立品牌)',
    'Nick Fouquet (CA)': 'Nick Fouquet (独立品牌)',
    'Ruslan Baginskiy (Ukraine)': 'Ruslan Baginskiy (独立品牌)',
    'Emma Brewin (UK)': 'Emma Brewin (独立品牌)',
    'Lock & Co. Hatters (UK)': 'Lock & Co. Hatters (私营家族企业)',
    'Stetson (TX)': 'Stetson (独立品牌)',
    'Bailey (CA)': 'Bailey Hats (独立品牌)',
    'Borsalino (Italy)': 'Borsalino (独立品牌)',
    'Kangol (UK)': 'Kangol (独立品牌)',
    'New Era (NY)': 'New Era Cap (私营家族企业)',
    "'47 (MA)": "'47 Brand (私营家族企业)",
    'Mitchell & Ness (PA)': 'Mitchell & Ness (Fanatics)',
    'Fanatics (FL)': 'Fanatics, Inc.',
    'Lids (IN)': 'Lids (独立品牌)',
    'Hat Club (AZ)': 'Hat Club (独立品牌)',
    'Ebbets Field Flannels (WA)': 'Ebbets Field Flannels (独立品牌)',
    'Norse Projects (Denmark)': 'Norse Projects (独立品牌)',
    'Wood Wood (Denmark)': 'Wood Wood (独立品牌)',
    'Han Kjøbenhavn (Denmark)': 'Han Kjøbenhavn (独立品牌)',
    'Samsøe Samsøe (Denmark)': 'Samsøe Samsøe (独立品牌)',
    'Baum und Pferdgarten (Denmark)': 'Baum und Pferdgarten (独立品牌)',
    'Gestuz (Denmark)': 'Gestuz (独立品牌)',
    'By Malene Birger (Denmark)': 'By Malene Birger (独立品牌)',
    'Henrik Vibskov (Denmark)': 'Henrik Vibskov (独立品牌)',
    'Astrid Andersen (Denmark)': 'Astrid Andersen (独立品牌)',
    'Soulland (Denmark)': 'Soulland (独立品牌)',
    'Libertine-Libertine (Denmark)': 'Libertine-Libertine (独立品牌)',
    'Mads Nørgaard (Denmark)': 'Mads Nørgaard (独立品牌)',
    'Stine Goya (Denmark)': 'Stine Goya (独立品牌)',
    'Rotate (Denmark)': 'Rotate (独立品牌)',
    'Cecilie Bahnsen (Denmark)': 'Cecilie Bahnsen (独立品牌)',
    'Ganni (Denmark)': 'Ganni (独立品牌)',
    'Heliot Emil (Denmark)': 'Heliot Emil (独立品牌)',
    'Acler (AU)': 'Acler (独立品牌)',
    'Bec + Bridge (AU)': 'Bec + Bridge (独立品牌)',
    'Sir the Label (AU)': 'Sir the Label (独立品牌)',
    'Christopher Esber (AU)': 'Christopher Esber (独立品牌)',
    'Dion Lee (AU)': 'Dion Lee (独立品牌)',
    'Zimmermann (AU)': 'Zimmermann (Advent International)',
    'Camilla and Marc (AU)': 'Camilla and Marc (独立品牌)',
    'Aje (AU)': 'Aje (独立品牌)',
    'Shona Joy (AU)': 'Shona Joy (独立品牌)',
    'Bassike (AU)': 'Bassike (独立品牌)',
    'Jac + Jack (AU)': 'Jac + Jack (独立品牌)',
    'Viktoria & Woods (AU)': 'Viktoria & Woods (独立品牌)',
    'Lee Mathews (AU)': 'Lee Mathews (独立品牌)',
    'Matteau (AU)': 'Matteau (独立品牌)',
    'St. Agni (AU)': 'St. Agni (独立品牌)',
    'Posse (AU)': 'Posse (独立品牌)',
    'Spell & The Gypsy Collective (AU)': 'Spell & The Gypsy Collective (独立品牌)',
    'Faithfull The Brand (AU)': 'Faithfull The Brand (独立品牌)',
    'Hansen & Gretel (AU)': 'Hansen & Gretel (独立品牌)',
    'Réalisation Par (AU)': 'Réalisation Par (独立品牌)',
    'With Jéan (AU)': 'With Jéan (独立品牌)',
    'Lioness (AU)': 'Lioness (独立品牌)',
    'Meshki (AU)': 'Meshki (独立品牌)',
    'White Fox Boutique (AU)': 'White Fox Boutique (独立品牌)',
    'Sabbi (AU)': 'Sabbi (独立品牌)',
    'Pe Nation (AU)': 'P.E Nation (独立品牌)',
    'Nagnata (AU)': 'Nagnata (独立品牌)',
    'The Upside (AU)': 'The Upside (独立品牌)',
    'Nimble Activewear (AU)': 'Nimble Activewear (独立品牌)',
    'Lorna Jane (AU)': 'Lorna Jane (私营家族企业)',
    'LSKD (AU)': 'LSKD (独立品牌)',
    'Muscle Republic (AU)': 'Muscle Republic (独立品牌)',
    'STAX (AU)': 'STAX (独立品牌)',
    'Elite Eleven (AU)': 'Elite Eleven (独立品牌)',
    'YoungLA (CA)': 'YoungLA (独立品牌)',
    'Gymreapers (ID)': 'Gymreapers (独立品牌)',
    'Rawgear (CA)': 'Rawgear (独立品牌)',
    'Alphalete (TX)': 'Alphalete (独立品牌)',
    'Buffbunny (TX)': 'Buffbunny Collection (独立品牌)',
    'Balance Athletica (CO)': 'Balance Athletica (独立品牌)',
    'Tier Activewear (CA)': 'Tier Activewear (独立品牌)',
    'Vitality (CA)': 'Vitality (独立品牌)',
    'Oner Active (UK)': 'Oner Active (独立品牌)',
    'DFYNE (UK)': 'DFYNE (独立品牌)',
    'Adanola (UK)': 'Adanola (独立品牌)',
    'Aybl (UK)': 'AYBL (独立品牌)',
    'TALA (UK)': 'TALA (独立品牌)',
    'LNDR (UK)': 'LNDR (独立品牌)',
    'Varley (UK active)': 'Varley (独立品牌)',
    'Sweaty Betty (UK active)': 'Sweaty Betty (Wolverine Worldwide)',
    'Gymshark (UK active)': 'Gymshark (独立品牌)',
    'Castore (UK)': 'Castore (独立品牌)',
    'Gym King (UK)': 'Gym King (独立品牌)',
    'Vanquish Fitness (UK)': 'Vanquish Fitness (独立品牌)',
    'Physiq Apparel (UK)': 'Physiq Apparel (独立品牌)',
    ' Pursue Fitness (UK)': 'Pursue Fitness (独立品牌)',
    'BSc (Body Science) (AU)': 'BSc (Body Science) (独立品牌)',
    'Ryderwear (AU)': 'Ryderwear (独立品牌)',
    'Doyoueven (AU)': 'Doyoueven (独立品牌)',
    'CSB (AU)': 'CSB (独立品牌)',
    'Muscle Nation (AU)': 'Muscle Nation (独立品牌)',
    'Echt (AU)': 'Echt (独立品牌)',
    'Jaggad (AU)': 'Jaggad (独立品牌)',
    'The Wod Life (AU)': 'The Wod Life (独立品牌)',
    'Born Tough (CA)': 'Born Tough (独立品牌)',
    'Jed North (CA)': 'Jed North (独立品牌)',
    'Jack West (CA)': 'Jack West (独立品牌)',
    'Barbell Brigade (CA)': 'Barbell Brigade (独立品牌)',
    'Darc Sport (CA)': 'Darc Sport (独立品牌)',
    'GASP (Sweden)': 'GASP (独立品牌)',
    'Better Bodies (Sweden)': 'Better Bodies (独立品牌)',
    'Gorilla Wear (NL)': 'Gorilla Wear (独立品牌)',
    'Barebells (Sweden)': 'Barebells (独立品牌)',
    'NOCCO (Sweden)': 'NOCCO (独立品牌)',
    'Vitamin Well (Sweden)': 'Vitamin Well (独立品牌)',
    'Barebells Functional Foods (Sweden)': 'Barebells (独立品牌)',
    'Grenade (UK)': 'Grenade (Mondelez收购)',
    'Fulfil (Ireland)': 'Fulfil Nutrition (独立品牌)',
    'Quest Nutrition (CA)': 'Quest Nutrition (Simply Good Foods)',
    'ONE Brands (NC)': 'ONE Brands (Hershey收购)',
    'Think! (CA)': 'Think! (Glanbia)',
    'RXBAR (IL)': 'RXBAR (Kellogg)',
    'Lärabar (CO)': "Lärabar (General Mills)",
    'Kind (NY)': 'Kind Snacks (Mars)',
    'Clif Bar (CA)': 'Clif Bar & Company (Mondelez收购)',
    'Luna Bar (CA)': 'Clif Bar & Company (Mondelez)',
    'Perfect Bar (CA)': 'Perfect Bar (Mondelez收购)',
    'No Cow (CO)': 'No Cow (独立品牌)',
    'GoMacro (WI)': 'GoMacro (独立品牌)',
    'Bobo\'s (CO)': "Bobo's (独立品牌)",
    'Skout Organic (OR)': 'Skout Organic (独立品牌)',
    'Kate\'s Real Food (WY)': "Kate's Real Food (独立品牌)",
    'Probar (UT)': 'Probar (独立品牌)',
    'Picky Bars (OR)': 'Picky Bars (独立品牌)',
    'Honey Stinger (CO)': 'Honey Stinger (独立品牌)',
    'GU Energy (CA)': 'GU Energy Labs (独立品牌)',
    'Clif Shot (CA)': 'Clif Bar & Company (Mondelez)',
    'Maurten (Sweden)': 'Maurten (独立品牌)',
    'Precision Fuel & Hydration (UK)': 'Precision Fuel & Hydration (独立品牌)',
    'SiS (Science in Sport) (UK)': 'Science in Sport plc (上市公司)',
    'Torq (UK)': 'Torq Fitness (独立品牌)',
    'High5 (UK)': 'High5 (独立品牌)',
    'Skratch Labs (CO)': 'Skratch Labs (独立品牌)',
    'Tailwind Nutrition (CO)': 'Tailwind Nutrition (独立品牌)',
    'Nuun (WA)': 'Nuun (Nestlé Health Science)',
    'Liquid I.V. (CA)': 'Liquid I.V. (Unilever收购)',
    'DripDrop (CA)': 'DripDrop ORS (独立品牌)',
    'Hydrant (NY)': 'Hydrant (独立品牌)',
    'Cure Hydration (NY)': 'Cure Hydration (独立品牌)',
    'LMNT (FL)': 'LMNT (独立品牌)',
    'Re-Lyte (UT)': 'Re-Lyte (Redmond Life)',
    'Ultima (MI)': 'Ultima Replenisher (独立品牌)',
    'Vital Proteins (IL)': 'Vital Proteins (Nestlé Health Science)',
    'Ancient Nutrition (FL)': 'Ancient Nutrition (独立品牌)',
    'Primal Kitchen (CA)': 'Primal Kitchen (Kraft Heinz收购)',
    'Bulletproof (WA)': 'Bulletproof (独立品牌)',
    'Onnit (TX)': 'Onnit (Unilever收购)',
    'Garden of Life (FL)': 'Garden of Life (Nestlé)',
    'MegaFood (NH)': 'MegaFood (独立品牌)',
    'New Chapter (VT)': 'New Chapter (Procter & Gamble)',
    'Gaia Herbs (NC)': 'Gaia Herbs (独立品牌)',
    'Herb Pharm (OR)': 'Herb Pharm (独立品牌)',
    'WishGarden Herbs (CO)': 'WishGarden Herbs (独立品牌)',
    'Urban Moonshine (VT)': 'Urban Moonshine (独立品牌)',
    'Anima Mundi (NY)': 'Anima Mundi Herbals (独立品牌)',
    'Sun Potion (CA)': 'Sun Potion (独立品牌)',
    'Moon Juice (CA)': 'Moon Juice (独立品牌)',
    'Sakara Life (NY)': 'Sakara Life (独立品牌)',
    'Daily Harvest (NY)': 'Daily Harvest (独立品牌)',
    'Splendid Spoon (NY)': 'Splendid Spoon (独立品牌)',
    'Mosaic Foods (NY)': 'Mosaic Foods (独立品牌)',
    'Thistle (CA)': 'Thistle (独立品牌)',
    'Territory Foods (DC)': 'Territory Foods (独立品牌)',
    'CookUnity (NY)': 'CookUnity (独立品牌)',
    'Factor (IL)': 'Factor (HelloFresh收购)',
    'Freshly (NY)': 'Freshly (Nestlé, 已关闭)',
    'Snap Kitchen (TX)': 'Snap Kitchen (独立品牌)',
    'Trifecta (CA)': 'Trifecta Nutrition (独立品牌)',
    'Pete\'s Paleo (CA)': "Pete's Paleo (独立品牌)",
    'The Good Kitchen (NC)': 'The Good Kitchen (独立品牌)',
    'Ice Age Meals (CO)': 'Ice Age Meals (独立品牌)',
    'Paleo On The Go (FL)': 'Paleo On The Go (独立品牌)',
    'True Primal (CA)': 'True Primal (独立品牌)',
    'Kettlebell Kitchen (NY)': 'Kettlebell Kitchen (独立品牌)',
    'Methodology (CA)': 'Methodology (独立品牌)',
    'Provenance Meals (NY)': 'Provenance Meals (独立品牌)',
    'Epicured (NY)': 'Epicured (独立品牌)',
    'ModifyHealth (GA)': 'ModifyHealth (独立品牌)',
    'Sunbasket (CA)': 'Sunbasket (独立品牌)',
    'Green Chef (CO)': 'Green Chef (HelloFresh收购)',
    'Gobble (CA)': 'Gobble (独立品牌)',
    'Marley Spoon (Berlin)': 'Marley Spoon (上市公司)',
    'Dinnerly (Berlin)': 'Marley Spoon',
    'Home Chef (IL)': 'Home Chef (Kroger收购)',
    'Blue Apron (NY)': 'Blue Apron (Wonder收购)',
    'HelloFresh (Berlin)': 'HelloFresh SE (上市公司)',
    'EveryPlate (Berlin)': 'HelloFresh SE',
    'Purple Carrot (MA)': 'Purple Carrot (独立品牌)',
    'Veestro (CA)': 'Veestro (独立品牌)',
    'MamaSezz (VT)': 'MamaSezz (独立品牌)',
    'Splendid Spoon (vegan)': 'Splendid Spoon (独立品牌)',
    'LeafSide (AZ)': 'LeafSide (独立品牌)',
    'PlantPure (NC)': 'PlantPure (独立品牌)',
    'Mosaic (NY)': 'Mosaic Foods (独立品牌)',
    'Mosaic Foods (vegan)': 'Mosaic Foods (独立品牌)',
    'Willa\'s (NY)': "Willa's (独立品牌)",
    'Oatly (Sweden)': 'Oatly Group AB (上市公司)',
    'Califia Farms (CA)': 'Califia Farms (独立品牌)',
    'Minor Figures (UK)': 'Minor Figures (独立品牌)',
    'Ripple Foods (CA)': 'Ripple Foods (独立品牌)',
    'Elmhurst 1925 (NY)': 'Elmhurst 1925 (独立品牌)',
    'MALK Organics (TX)': 'MALK Organics (独立品牌)',
    'Three Trees (CA)': 'Three Trees (独立品牌)',
    'Forager Project (CA)': 'Forager Project (独立品牌)',
    'Kite Hill (CA)': 'Kite Hill (独立品牌)',
    'Miyoko\'s Creamery (CA)': "Miyoko's Creamery (独立品牌)",
    'Treeline (NY)': 'Treeline Cheese (独立品牌)',
    'VioLife (Greece)': 'VioLife (Upfield)',
    'Violife (Greece)': 'Upfield',
    'Follow Your Heart (CA)': 'Follow Your Heart (独立品牌)',
    'Daiya (Canada)': 'Daiya Foods (Otsuka Pharmaceutical)',
    'Chao (WA)': 'Field Roast (Maple Leaf Foods)',
    'Field Roast (WA)': 'Field Roast (Maple Leaf Foods)',
    'Tofurky (OR)': 'Tofurky (独立品牌)',
    'Lightlife (MA)': 'Lightlife (Maple Leaf Foods)',
    'Yves Veggie Cuisine (Canada)': 'Yves Veggie Cuisine (Hain Celestial)',
    'Gardein (Canada)': 'Gardein (Conagra Brands)',
    'MorningStar Farms (MI)': 'MorningStar Farms (Kellogg)',
    'Boca (IL)': 'Boca Foods (Kraft Heinz)',
    'Beyond Meat (CA)': 'Beyond Meat, Inc. (上市公司)',
    'Impossible Foods (CA)': 'Impossible Foods (独立品牌)',
    'Dr. Praeger\'s (NJ)': "Dr. Praeger's (独立品牌)",
    'Hilary\'s (KS)': "Hilary's (独立品牌)",
    'Alpha Foods (CA)': 'Alpha Foods (独立品牌)',
    'Before the Butcher (CA)': 'Before the Butcher (独立品牌)',
    'Good Catch (PA)': 'Good Catch (独立品牌)',
    'Sophie\'s Kitchen (CA)': "Sophie's Kitchen (独立品牌)",
    'Quorn (UK)': 'Quorn Foods (Monde Nissin)',
    'Vivera (NL)': 'Vivera (JBS)',
    'LikeMeat (Germany)': 'LikeMeat (LIVEKINDLY Collective)',
    'The Fry Family Food Co. (South Africa)': 'Fry Family Food Co. (LIVEKINDLY Collective)',
    'Oumph! (Sweden)': 'Oumph! (LIVEKINDLY Collective)',
    'No Evil Foods (NC)': 'No Evil Foods (独立品牌)',
    'Upton\'s Naturals (IL)': "Upton's Naturals (独立品牌)",
    'Louisville Vegan Jerky Co. (KY)': 'Louisville Vegan Jerky Co. (独立品牌)',
    'Primal Spirit Foods (PA)': 'Primal Spirit Foods (独立品牌)',
    'Pan\'s Mushroom Jerky (OR)': "Pan's Mushroom Jerky (独立品牌)",
    'Moku (CA)': 'Moku Foods (独立品牌)',
    'All Y\'alls Foods (TX)': "All Y'alls Foods (独立品牌)",
    'Solely (CA)': 'Solely (独立品牌)',
    'Bear (UK)': 'Bear Nibbles (独立品牌)',
    'Barnana (CA)': 'Barnana (独立品牌)',
    'Rind Snacks (NY)': 'Rind Snacks (独立品牌)',
    'Spudsy (CA)': 'Spudsy (独立品牌)',
    'Peatos (CA)': 'Peatos (独立品牌)',
    'Hippeas (NY)': 'Hippeas (独立品牌)',
    'Pirate\'s Booty (NY)': "Pirate's Booty (Hershey)",
    'Smartfood (MA)': 'Smartfood (PepsiCo)',
    'Popchips (CA)': 'Popchips (独立品牌)',
    'Beanfields (CA)': 'Beanfields (独立品牌)',
    'Siete (TX)': 'Siete (PepsiCo收购)',
    'Late July (CT)': 'Late July (Campbell Soup)',
    'Tortilla Chips by Siete': 'Siete (PepsiCo)',
    'Paqui (TX)': 'Paqui (Hershey)',
    'Takis (Mexico)': 'Takis (Barcel/Grupo Bimbo)',
    'Quest Chips (CA)': 'Quest Nutrition (Simply Good Foods)',
    'Wilde Chips (CO)': 'Wilde Brands (独立品牌)',
    'Whisps (NY)': 'Whisps (独立品牌)',
    'Moon Cheese (WA)': 'Moon Cheese (独立品牌)',
    'ParmCrisps (WI)': 'ParmCrisps (独立品牌)',
    'Sonoma Creamery (CA)': 'Sonoma Creamery (独立品牌)',
    'Just the Cheese (WI)': 'Just the Cheese (独立品牌)',
    'Cheese Bits (CA)': 'Cheese Bits (独立品牌)',
    'Cello Whisps (NY)': 'Whisps (独立品牌)',
    'Biena (MA)': 'Biena Snacks (独立品牌)',
    'The Good Bean (CA)': 'The Good Bean (独立品牌)',
    'Saffron Road (CT)': 'Saffron Road (独立品牌)',
    'Brami (NY)': 'Brami (独立品牌)',
    'Bada Bean Bada Boom (FL)': 'Bada Bean Bada Boom (独立品牌)',
    'Enlightened (NY)': 'Enlightened (独立品牌)',
    'Yasso (MA)': 'Yasso (Unilever收购)',
    'Halo Top (CA)': 'Halo Top (Wells Enterprises)',
    'Nick\'s (Sweden)': "Nick's (独立品牌)",
    'Rebel Creamery (UT)': 'Rebel Creamery (独立品牌)',
    'Keto Pint (OR)': 'Keto Pint (独立品牌)',
    'Arctic Zero (CA)': 'Arctic Zero (独立品牌)',
    'Sweet Nothings (CA)': 'Sweet Nothings (独立品牌)',
    'Chloe\'s (NY)': "Chloe's (独立品牌)",
    'Outshine (IL)': 'Outshine (Nestlé)',
    'GoodPop (TX)': 'GoodPop (独立品牌)',
    'Deebee\'s (Canada)': "DeeBee's Organics (独立品牌)",
    'JonnyPops (MN)': 'JonnyPops (独立品牌)',
    'Fudgsicle (NJ)': 'Fudgsicle (Unilever)',
    'Creamsicle (NJ)': 'Creamsicle (Unilever)',
    'Popsicle (NJ)': 'Popsicle (Unilever)',
    'Klondike (CO)': 'Klondike (Unilever)',
    'Magnum (Belgium)': 'Magnum (Unilever)',
    'Talenti (MN)': 'Talenti (Unilever)',
    'Breyers (NJ)': 'Breyers (Unilever)',
    'Ben & Jerry\'s (VT)': "Ben & Jerry's (Unilever)",
    'Häagen-Dazs (NY)': 'Häagen-Dazs (General Mills, 美国/Nestlé, 国际)',
    'Van Leeuwen (NY)': 'Van Leeuwen Ice Cream (独立品牌)',
    'Jeni\'s (OH)': "Jeni's Splendid Ice Creams (独立品牌)",
    'McConnell\'s (CA)': "McConnell's Fine Ice Creams (独立品牌)",
    'Salt & Straw (OR)': 'Salt & Straw (独立品牌)',
    'Ample Hills (NY)': 'Ample Hills Creamery (独立品牌)',
    'Morgenstern\'s (NY)': "Morgenstern's Finest Ice Cream (独立品牌)",
    'OddFellows (NY)': 'OddFellows Ice Cream Co. (独立品牌)',
    'Big Gay Ice Cream (NY)': 'Big Gay Ice Cream (独立品牌)',
    'Milk Bar (NY)': 'Milk Bar (独立品牌)',
    'Coolhaus (CA)': 'Coolhaus (独立品牌)',
    'Cado (IA)': 'Cado (独立品牌)',
    'NadaMoo! (TX)': 'NadaMoo! (独立品牌)',
    'Cosmic Bliss (OR)': 'Cosmic Bliss (独立品牌)',
    'Coconut Bliss (OR)': 'Cosmic Bliss (独立品牌)',
    'Oatly Frozen (Sweden)': 'Oatly Group AB',
    'Wildgood (CA)': 'Wildgood (独立品牌)',
    'Sun Scoop (NY)': 'Sun Scoop (独立品牌)',
    'Snow Monkey (CA)': 'Snow Monkey (独立品牌)',
    'Banan (HI)': 'Banan (独立品牌)',
    'Mustang (NY)': 'Mustang (独立品牌)',
    'Agua Bendita (Colombia)': 'Agua Bendita (独立品牌)',
    'Johanna Ortiz (Colombia)': 'Johanna Ortiz (独立品牌)',
    'Silvia Tcherassi (Colombia)': 'Silvia Tcherassi (独立品牌)',
    'Pepa Loves (Colombia)': 'Pepa Loves (独立品牌)',
    'Mercedes Salazar (Colombia)': 'Mercedes Salazar (独立品牌)',
    'Alado (Colombia)': 'Alado (独立品牌)',
    'Onda de Mar (Colombia)': 'Onda de Mar (独立品牌)',
    'Ancora (Colombia)': 'Ancora (独立品牌)',
    'Mola Sasa (Colombia)': 'Mola Sasa (独立品牌)',
    'Verde Limon (Colombia)': 'Verde Limon (独立品牌)',
    'Beatriz Camacho (Colombia)': 'Beatriz Camacho (独立品牌)',
    'Laura Laurens (Colombia)': 'Laura Laurens (独立品牌)',
    'Esteban Cortazar (Colombia)': 'Esteban Cortazar (独立品牌)',
    'Kika Vargas (Colombia)': 'Kika Vargas (独立品牌)',
    'Auralis (Puerto Rico)': 'Auralis (独立品牌)',
    'Stella Nolasco (Puerto Rico)': 'Stella Nolasco (独立品牌)',
    'María de Orleáns (Puerto Rico)': 'María de Orleáns (独立品牌)',
    'Nonô (Brazil)': 'Nonô (独立品牌)',
    'PatBO (Brazil)': 'PatBO (独立品牌)',
    'Farm Rio (Brazil)': 'Farm Rio (独立品牌)',
    'Água de Coco (Brazil)': 'Água de Coco (独立品牌)',
    'Lenny Niemeyer (Brazil)': 'Lenny Niemeyer (独立品牌)',
    'Adriana Degreas (Brazil)': 'Adriana Degreas (独立品牌)',
    'Triya (Brazil)': 'Triya (独立品牌)',
    'Haight (Brazil)': 'Haight (独立品牌)',
    'Vix (Brazil)': 'Vix (独立品牌)',
    'Osklen (Brazil)': 'Osklen (独立品牌)',
    'Alexandre Birman (Brazil)': 'Alexandre Birman (独立品牌)',
    'Schutz (Brazil)': 'Schutz (Arezzo&Co)',
    'Arezzo (Brazil)': 'Arezzo&Co (上市公司)',
    'Melissa (Brazil)': 'Melissa (Grendene)',
    'Grendene (Brazil)': 'Grendene (上市公司)',
    'Ipanema (Brazil)': 'Ipanema (Grendene)',
    'Rider (Brazil)': 'Rider (Grendene)',
    'Cartago (Brazil)': 'Cartago (独立品牌)',
    'Havaianas (Brazil)': 'Havaianas (Alpargatas)',
    'Alpargatas (Brazil)': 'Alpargatas (上市公司)',
    'Topper (Argentina)': 'Topper (Alpargatas Brazil)',
    'Mizuno (Brazil)': 'Mizuno do Brasil (Alpargatas, 已出售给Grupo Dass)',
    'Rainha (Brazil)': 'Rainha (Alpargatas)',
    'Sete Léguas (Brazil)': 'Sete Léguas (独立品牌)',
    'Dakota (Brazil)': 'Dakota (独立品牌)',
    'Moleca (Brazil)': 'Moleca (独立品牌)',
    'Piccadilly (Brazil)': 'Piccadilly (独立品牌)',
    'Vizzano (Brazil)': 'Vizzano (独立品牌)',
    'Beira Rio (Brazil)': 'Beira Rio (独立品牌)',
    'Molekinha (Brazil)': 'Molekinha (独立品牌)',
    'Modare (Brazil)': 'Modare (独立品牌)',
    'Bibbi (Brazil)': 'Bibbi (独立品牌)',
    'Kildare (Brazil)': 'Kildare (独立品牌)',
    'Pampili (Brazil)': 'Pampili (独立品牌)',
    'Bebel (Brazil)': 'Bebel (独立品牌)',
    'Tip Toey Joey (Brazil)': 'Tip Toey Joey (独立品牌)',
    'Pé de Chumbo (Brazil)': 'Pé de Chumbo (独立品牌)',
    'Pequinch (Brazil)': 'Pequinch (独立品牌)',
    'Planet Girls (Brazil)': 'Planet Girls (独立品牌)',
    'Tigor T. Tigre (Brazil)': 'Tigor T. Tigre (独立品牌)',
    'Tyrol (Brazil)': 'Tyrol (独立品牌)',
    'Democrata (Brazil)': 'Democrata (独立品牌)',
    'Ferracini (Brazil)': 'Ferracini (独立品牌)',
    'Via Uno (Brazil)': 'Via Uno (独立品牌)',
    'Bebecê (Brazil)': 'Bebecê (独立品牌)',
    'Loucos & Santos (Brazil)': 'Loucos & Santos (独立品牌)',
    'Jorge Bischoff (Brazil)': 'Jorge Bischoff (独立品牌)',
    'Constança Basto (Brazil)': 'Constança Basto (独立品牌)',
    'Santa Lolla (Brazil)': 'Santa Lolla (独立品牌)',
    'Capodarte (Brazil)': 'Capodarte (独立品牌)',
    'Anacapri (Brazil)': 'Anacapri (独立品牌)',
    'Carmen Steffens (Brazil)': 'Carmen Steffens (独立品牌)',
    'Raphaella Booz (Brazil)': 'Raphaella Booz (独立品牌)',
    'Morena Rosa (Brazil)': 'Morena Rosa (独立品牌)',
    'Maria Filó (Brazil)': 'Maria Filó (独立品牌)',
    'Cantão (Brazil)': 'Cantão (独立品牌)',
    'Richards (Brazil)': 'Richards (独立品牌)',
    'Richards (Brazil menswear)': 'Richards (独立品牌)',
    'Vila Romana (Brazil)': 'Vila Romana (独立品牌)',
    'VR (Brazil)': 'VR (Vila Romana)',
    'Brooksfield (Brazil)': 'Brooksfield (独立品牌)',
    'Cori (Brazil)': 'Cori (独立品牌)',
    'Ellus (Brazil)': 'Ellus (独立品牌)',
    'Bobstore (Brazil)': 'Bobstore (独立品牌)',
    'Cavalera (Brazil)': 'Cavalera (独立品牌)',
    'Zoomp (Brazil)': 'Zoomp (独立品牌)',
    'M.Officer (Brazil)': 'M.Officer (独立品牌)',
    'Fórum (Brazil)': 'Fórum (AMC Têxtil)',
    'Triton (Brazil)': 'Triton (AMC Têxtil)',
    'Colcci (Brazil)': 'Colcci (AMC Têxtil)',
    'Coca-Cola Clothing (Brazil)': 'AMC Têxtil (授权)',
    'SOMOS (Brazil)': 'SOMOS (独立品牌)',
    'Handred (Brazil)': 'Handred (独立品牌)',
    'Thear (Brazil)': 'Thear (独立品牌)',
    'Gissa (Brazil)': 'Gissa (独立品牌)',
    'Giovanna Baby (Brazil)': 'Giovanna Baby (独立品牌)',
    'Lilica Ripilica (Brazil)': 'Lilica Ripilica (独立品牌)',
    'Tigor (Brazil)': 'Tigor T. Tigre (独立品牌)',
    'Milal (Brazil)': 'Milal (独立品牌)',
    'Brandili (Brazil)': 'Brandili (独立品牌)',
    'Marisol (Brazil)': 'Marisol (独立品牌)',
    'Kyly (Brazil)': 'Kyly (独立品牌)',
    'Malwee (Brazil)': 'Malwee (独立品牌)',
    'Hering (Brazil)': 'Hering (Grupo SBF)',
    'Dzarm (Brazil)': 'Dzarm (独立品牌)',
    'Ogochi (Brazil)': 'Ogochi (独立品牌)',
    'Alphorria (Brazil)': 'Alphorria (独立品牌)',
    'Shoulder (Brazil)': 'Shoulder (独立品牌)',
    'Dona Flor (Brazil)': 'Dona Flor (独立品牌)',
    'Lunender (Brazil)': 'Lunender (独立品牌)',
    'Maria Valentina (Brazil)': 'Maria Valentina (独立品牌)',
    'Calle (Brazil)': 'Calle (独立品牌)',
    'Lança Perfume (Brazil)': 'Lança Perfume (独立品牌)',
    'Ateen (Brazil)': 'Ateen (独立品牌)',
    'Skazi (Brazil)': 'Skazi (独立品牌)',
    'Track & Field (Brazil)': 'Track & Field (独立品牌)',
    'Live! (Brazil)': 'Live! (独立品牌)',
    'Body for Sure (Brazil)': 'Body for Sure (独立品牌)',
    'Labellamafia (Brazil)': 'Labellamafia (独立品牌)',
    'Blueman (Brazil)': 'Blueman (独立品牌)',
    'New Order (Brazil)': 'New Order (独立品牌)',
    'Rosa Chá (Brazil)': 'Rosa Chá (独立品牌)',
    'Cia. Marítima (Brazil)': 'Cia. Marítima (独立品牌)',
    'Salinas (Brazil)': 'Salinas (独立品牌)',
    'Bum (Brazil)': 'Bum (独立品牌)',
    'Blue Man (Brazil)': 'Blue Man (独立品牌)',
    'Squalo (Brazil)': 'Squalo (独立品牌)',
    'Hope (Brazil)': 'Hope (独立品牌)',
    'Valisere (Brazil)': 'Valisere (独立品牌)',
    'Liz (Brazil)': 'Liz (独立品牌)',
    'Duloren (Brazil)': 'Duloren (独立品牌)',
    'DeMillus (Brazil)': 'DeMillus (独立品牌)',
    'Trifil (Brazil)': 'Trifil (独立品牌)',
    'Scalina (Brazil)': 'Scalina (独立品牌)',
    'Lupo (Brazil)': 'Lupo (独立品牌)',
    'Mash (Brazil)': 'Mash (独立品牌)',
    'Zorba (Brazil)': 'Zorba (独立品牌)',
    'Puket (Brazil)': 'Puket (独立品牌)',
    'Imaginarium (Brazil)': 'Imaginarium (独立品牌)',
    'Morana (Brazil)': 'Morana (独立品牌)',
    'Pandora (Brazil)': 'Pandora (上市公司)',
    'Vivara (Brazil)': 'Vivara (上市公司)',
    'Monte Carlo (Brazil)': 'Monte Carlo (独立品牌)',
    'HStern (Brazil)': 'H.Stern (独立品牌)',
    'Swarovski (Austria)': 'Swarovski (私营家族企业)',
    'Pandora (Denmark)': 'Pandora (上市公司)',
    'Tiffany & Co. (USA)': 'LVMH',
    'Cartier (Richemont)': 'Richemont',
    'Van Cleef & Arpels (Richemont)': 'Richemont',
    'Bulgari (LVMH)': 'LVMH',
    'Buccellati (Richemont)': 'Richemont',
    'Mikimoto (Japan)': 'Mikimoto (上市公司)',
    'Tasaki (Japan)': 'Tasaki (独立品牌)',
    'Niessing (Germany)': 'Niessing (独立品牌)',
    'Wellendorff (Germany)': 'Wellendorff (私营家族企业)',
    'Chopard (Switzerland)': 'Chopard (私营家族企业)',
    'Graff (UK)': 'Graff Diamonds (私营家族企业)',
    'De Beers (UK)': 'De Beers (Anglo American)',
    'Forevermark (UK)': 'De Beers (Anglo American)',
    'Hearts On Fire (USA)': 'Hearts On Fire (Chow Tai Fook)',
    'Brilliant Earth (USA)': 'Brilliant Earth (上市公司)',
    'Blue Nile (USA)': 'Blue Nile (Signet Jewelers)',
    'James Allen (USA)': 'James Allen (Signet Jewelers)',
    'Zales (USA)': 'Zales (Signet Jewelers)',
    'Kay Jewelers (USA)': 'Kay Jewelers (Signet Jewelers)',
    'Jared (USA)': 'Jared (Signet Jewelers)',
    'Banter by Piercing Pagoda (USA)': 'Banter (Signet Jewelers)',
    'Peoples Jewellers (Canada)': 'Peoples Jewellers (Signet Jewelers)',
    'Ernest Jones (UK)': 'Ernest Jones (Signet Jewelers)',
    'H.Samuel (UK)': 'H.Samuel (Signet Jewelers)',
    'Diamonds Direct (USA)': 'Diamonds Direct (Signet Jewelers)',
    'Rocksbox (USA)': 'Rocksbox (Signet Jewelers)',
    'Mejuri (Canada brand)': 'Mejuri (独立品牌)',
    'Ana Luisa (NY brand)': 'Ana Luisa (独立品牌)',
    'Gorjana (CA brand)': 'Gorjana (独立品牌)',
    'BaubleBar (NY brand)': 'BaubleBar (独立品牌)',
    'Catbird (NY brand)': 'Catbird (独立品牌)',
    'Wwake (NY)': 'Wwake (独立品牌)',
    'Sofia Zakia (Canada)': 'Sofia Zakia (独立品牌)',
    'Aurate (NY)': 'Aurate (独立品牌)',
    'Vrai (CA)': 'Vrai (独立品牌)',
    'Dorsey (CA)': 'Dorsey (独立品牌)',
    'Ring Concierge (NY)': 'Ring Concierge (独立品牌)',
    'Marrow Fine (CA)': 'Marrow Fine (独立品牌)',
    'Ceremony (CA)': 'Ceremony (独立品牌)',
    'Holden (NY)': 'Holden (独立品牌)',
    'Automic Gold (NY)': 'Automic Gold (独立品牌)',
    'Omi Woods (Canada)': 'Omi Woods (独立品牌)',
    'Kinn Studio (CA)': 'Kinn Studio (独立品牌)',
    'Missoma (UK)': 'Missoma (独立品牌)',
    'Missoma (北美)': 'Missoma (独立品牌)',
    'Monica Vinader (UK)': 'Monica Vinader (独立品牌)',
    'Edge of Ember (UK)': 'Edge of Ember (独立品牌)',
    'Alighieri (UK)': 'Alighieri (独立品牌)',
    'Completedworks (UK)': 'Completedworks (独立品牌)',
    'Bleue Burnham (UK)': 'Bleue Burnham (独立品牌)',
    'Rachel Jackson (UK)': 'Rachel Jackson London (独立品牌)',
    'Daisy London (UK)': 'Daisy London (独立品牌)',
    'Astley Clarke (UK)': 'Astley Clarke (独立品牌)',
    'Dinny Hall (UK)': 'Dinny Hall (独立品牌)',
    'Alex Monroe (UK)': 'Alex Monroe (独立品牌)',
    'Tatty Devine (UK)': 'Tatty Devine (独立品牌)',
    'Vivienne Westwood (UK)': 'Vivienne Westwood (独立品牌)',
    'Alexander McQueen (Kering)': 'Kering',
    'Gucci (Kering)': 'Kering',
    'Bottega Veneta (Kering)': 'Kering',
    'Saint Laurent (Kering)': 'Kering',
    'Balenciaga (Kering)': 'Kering',
    'Louis Vuitton (LVMH)': 'LVMH',
    'Dior (LVMH)': 'LVMH',
    'Fendi (LVMH)': 'LVMH',
    'Givenchy (LVMH)': 'LVMH',
    'Celine (LVMH)': 'LVMH',
    'Loewe (LVMH)': 'LVMH',
    'Marc Jacobs (LVMH)': 'LVMH',
    'Rimowa (LVMH)': 'LVMH',
    'Loro Piana (LVMH)': 'LVMH',
    'Berluti (LVMH)': 'LVMH',
    'Kenzo (LVMH)': 'LVMH',
    'Emilio Pucci (LVMH)': 'LVMH',
    'Chanel (Private)': 'Chanel (私营)',
    'Hermès (Independent)': 'Hermès International (上市公司)',
    'Prada (Public)': 'Prada Group (上市公司)',
    'Burberry (Public)': 'Burberry Group plc (上市公司)',
    'Moncler (Public)': 'Moncler Group (上市公司)',
    'Brunello Cucinelli (Public)': 'Brunello Cucinelli S.p.A. (上市公司)',
    'Zegna (Public)': 'Ermenegildo Zegna Group (上市公司)',
    'Canada Goose (Public)': 'Canada Goose Holdings Inc. (上市公司)',
    'Allbirds (Public)': 'Allbirds, Inc. (上市公司)',
    'On (Public)': 'On Holding AG (上市公司)',
    'Skechers (Public)': 'Skechers USA, Inc. (上市公司)',
    'Crocs (Public)': 'Crocs, Inc. (上市公司)',
    'Birkenstock (Public)': 'Birkenstock Holding plc (上市公司)',
    'Dr. Martens (Public)': 'Dr. Martens plc (上市公司)',
    'Levi Strauss (Public)': 'Levi Strauss & Co. (上市公司)',
    'Ralph Lauren (Public)': 'Ralph Lauren Corporation (上市公司)',
    'PVH (Public)': 'PVH Corp (上市公司)',
    'Capri Holdings (Public)': 'Capri Holdings (上市公司)',
    'Tapestry (Public)': 'Tapestry, Inc. (上市公司)',
    'VF Corp (Public)': 'VF Corporation (上市公司)',
    'Columbia Sportswear (Public)': 'Columbia Sportswear Company (上市公司)',
    'Wolverine Worldwide (Public)': 'Wolverine Worldwide (上市公司)',
    'Deckers Brands (Public)': 'Deckers Brands (上市公司)',
    'Nike (Public)': 'Nike, Inc. (上市公司)',
    'Adidas (Public)': 'Adidas AG (上市公司)',
    'Puma (Public)': 'Puma SE (上市公司)',
    'Under Armour (Public)': 'Under Armour, Inc. (上市公司)',
    'Lululemon (Public)': 'Lululemon Athletica, Inc. (上市公司)',
    'Gap Inc. (Public)': 'Gap Inc. (上市公司)',
    'American Eagle (Public)': 'American Eagle Outfitters, Inc. (上市公司)',
    'Abercrombie & Fitch (Public)': 'Abercrombie & Fitch Co. (上市公司)',
    'Urban Outfitters (Public)': 'Urban Outfitters, Inc. (URBN) (上市公司)',
    'Aritzia (Public)': 'Aritzia, Inc. (上市公司)',
    'Revolve (Public)': 'Revolve Group, Inc. (上市公司)',
    'Warby Parker (Public)': 'Warby Parker Inc. (上市公司)',
    'Torrid (Public)': 'Torrid Holdings Inc. (上市公司)',
    'YETI (Public)': 'YETI Holdings, Inc. (上市公司)',
    'Lands\' End (Public)': "Lands' End, Inc. (上市公司)",
    'Thule (Public)': 'Thule Group AB (上市公司)',
    'Oatly (Public)': 'Oatly Group AB (上市公司)',
    'Beyond Meat (Public)': 'Beyond Meat, Inc. (上市公司)',
    'Asics (Public)': 'ASICS Corporation (上市公司)',
    'Mizuno (Public)': 'Mizuno Corporation (上市公司)',
    'Goldwin (Public)': 'Goldwin Inc. (上市公司)',
    'Descente (Public)': 'Descente Ltd. (上市公司)',
    'Snow Peak (Public)': 'Snow Peak (上市公司)',
    'Fast Retailing (Public)': 'Fast Retailing (上市公司)',
    'Ryohin Keikaku (Public)': 'Ryohin Keikaku (上市公司)',
    'Mavi (Public)': 'Mavi (上市公司)',
    'Pandora (Public)': 'Pandora (上市公司)',
    'Vivara (Public)': 'Vivara (上市公司)',
    'Arezzo&Co (Public)': 'Arezzo&Co (上市公司)',
    'Grendene (Public)': 'Grendene (上市公司)',
    'Alpargatas (Public)': 'Alpargatas (上市公司)',
    'Grupo SBF (Public)': 'Grupo SBF (上市公司)',
    'Signet Jewelers (Public)': 'Signet Jewelers (上市公司)',
    'HelloFresh (Public)': 'HelloFresh SE (上市公司)',
    'Marley Spoon (Public)': 'Marley Spoon (上市公司)',
    'Science in Sport (Public)': 'Science in Sport plc (上市公司)',
    'Burberry Group (Public)': 'Burberry Group plc (上市公司)',
    'Hermès International (Public)': 'Hermès International (上市公司)',
    'Prada Group (Public)': 'Prada Group (上市公司)',
    'Moncler Group (Public)': 'Moncler Group (上市公司)',
    'Brunello Cucinelli SpA (Public)': 'Brunello Cucinelli S.p.A. (上市公司)',
    'Zegna Group (Public)': 'Ermenegildo Zegna Group (上市公司)',
    'Canada Goose Holdings (Public)': 'Canada Goose Holdings Inc. (上市公司)',
    'Allbirds Inc (Public)': 'Allbirds, Inc. (上市公司)',
    'On Holding (Public)': 'On Holding AG (上市公司)',
    'Skechers USA (Public)': 'Skechers USA, Inc. (上市公司)',
    'Crocs Inc (Public)': 'Crocs, Inc. (上市公司)',
    'Birkenstock Holding (Public)': 'Birkenstock Holding plc (上市公司)',
    'Dr Martens plc (Public)': 'Dr. Martens plc (上市公司)',
    'Levi Strauss & Co (Public)': 'Levi Strauss & Co. (上市公司)',
    'Ralph Lauren Corp (Public)': 'Ralph Lauren Corporation (上市公司)',
    'PVH Corp (Public)': 'PVH Corp (上市公司)',
    'Capri Holdings Ltd (Public)': 'Capri Holdings (上市公司)',
    'Tapestry Inc (Public)': 'Tapestry, Inc. (上市公司)',
    'VF Corporation (Public)': 'VF Corporation (上市公司)',
    'Columbia Sportswear Co (Public)': 'Columbia Sportswear Company (上市公司)',
    'Wolverine World Wide (Public)': 'Wolverine Worldwide (上市公司)',
    'Deckers Outdoor Corp (Public)': 'Deckers Brands (上市公司)',
    'Nike Inc (Public)': 'Nike, Inc. (上市公司)',
    'Adidas AG (Public)': 'Adidas AG (上市公司)',
    'Puma SE (Public)': 'Puma SE (上市公司)',
    'Under Armour Inc (Public)': 'Under Armour, Inc. (上市公司)',
    'Lululemon Athletica (Public)': 'Lululemon Athletica, Inc. (上市公司)',
    'Gap Inc (Public)': 'Gap Inc. (上市公司)',
    'American Eagle Outfitters (Public)': 'American Eagle Outfitters, Inc. (上市公司)',
    'Abercrombie & Fitch Co (Public)': 'Abercrombie & Fitch Co. (上市公司)',
    'URBN (Public)': 'Urban Outfitters, Inc. (URBN) (上市公司)',
    'Aritzia Inc (Public)': 'Aritzia, Inc. (上市公司)',
    'Revolve Group (Public)': 'Revolve Group, Inc. (上市公司)',
    'Warby Parker Inc (Public)': 'Warby Parker Inc. (上市公司)',
    'Torrid Holdings (Public)': 'Torrid Holdings Inc. (上市公司)',
    'YETI Holdings (Public)': 'YETI Holdings, Inc. (上市公司)',
    'Lands End Inc (Public)': "Lands' End, Inc. (上市公司)",
    'Thule Group (Public)': 'Thule Group AB (上市公司)',
    'Oatly Group (Public)': 'Oatly Group AB (上市公司)',
    'Beyond Meat Inc (Public)': 'Beyond Meat, Inc. (上市公司)',
    'ASICS Corp (Public)': 'ASICS Corporation (上市公司)',
    'Mizuno Corp (Public)': 'Mizuno Corporation (上市公司)',
    'Goldwin Inc (Public)': 'Goldwin Inc. (上市公司)',
    'Descente Ltd (Public)': 'Descente Ltd. (上市公司)',
    'Snow Peak Inc (Public)': 'Snow Peak (上市公司)',
    'Fast Retailing Co (Public)': 'Fast Retailing (上市公司)',
    'Ryohin Keikaku Co (Public)': 'Ryohin Keikaku (上市公司)',
    'Mavi Giyim (Public)': 'Mavi (上市公司)',
    'Pandora A/S (Public)': 'Pandora (上市公司)',
    'Vivara SA (Public)': 'Vivara (上市公司)',
    'Arezzo&Co SA (Public)': 'Arezzo&Co (上市公司)',
    'Grendene SA (Public)': 'Grendene (上市公司)',
    'Alpargatas SA (Public)': 'Alpargatas (上市公司)',
    'Grupo SBF SA (Public)': 'Grupo SBF (上市公司)',
    'Signet Jewelers Ltd (Public)': 'Signet Jewelers (上市公司)',
    'HelloFresh SE (Public)': 'HelloFresh SE (上市公司)',
    'Marley Spoon AG (Public)': 'Marley Spoon (上市公司)',
    'Science in Sport plc (Public)': 'Science in Sport plc (上市公司)',
}

def main():
    conn = sqlite3.connect(str(DB_PATH))
    cur = conn.cursor()
    
    count = 0
    for name, parent in PARENT_MAP.items():
        cur.execute(
            "UPDATE brands SET parent_company=?, updated_at=datetime('now') WHERE name=? AND (parent_company IS NULL OR parent_company='')",
            (parent, name)
        )
        if cur.rowcount > 0:
            count += 1
    
    conn.commit()
    
    remaining = cur.execute("SELECT COUNT(*) FROM brands WHERE parent_company IS NULL OR parent_company=''").fetchone()[0]
    total = cur.execute("SELECT COUNT(*) FROM brands").fetchone()[0]
    
    print(f"本轮补充: {count}")
    print(f"母公司覆盖率: {total - remaining}/{total} ({(total - remaining)/total*100:.1f}%)")
    conn.close()

if __name__ == '__main__':
    main()
